export const generateMockSiriCancellation = (subscriptionId: string, currentTime: string) => `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Siri xmlns="http://www.siri.org.uk/siri"
    xmlns:ns2="http://www.ifopt.org.uk/acsb"
    xmlns:ns3="http://www.ifopt.org.uk/ifopt"
    xmlns:ns4="http://datex2.eu/schema/2_0RC1/2_0"
    version="2.0">
  <ServiceDelivery>
  <ResponseTimestamp>${currentTime}</ResponseTimestamp>
  <ProducerRef>${subscriptionId}</ProducerRef>
  <Status>true</Status>
  <MoreData>false</MoreData>
    <SituationExchangeDelivery version="2.0">
      <ResponseTimestamp>${currentTime}</ResponseTimestamp>
      <SubscriberRef>247b3d8c-3675-4bae-aaa7-33fc15ead21c</SubscriberRef>
      <SubscriptionRef>98b6de8a-64d4-43f7-bacd-3c3d624b9903</SubscriptionRef>
      <Status>true</Status>
      <Situations>
        <PtSituationElement>
          <CreationTime>${currentTime}</CreationTime>
          <ParticipantRef>${subscriptionId}</ParticipantRef>
          <SituationNumber>8027633</SituationNumber>
          <Version>1</Version>
          <Progress>open</Progress>
          <Source>
            <SourceType>Other</SourceType>
          </Source>
          <ValidityPeriod>
            <StartTime>${currentTime}</StartTime>
            <EndTime>${currentTime}</EndTime>
          </ValidityPeriod>
          <MiscellaneousReason>unknown</MiscellaneousReason>
          <Affects>
            <VehicleJourneys>
              <AffectedVehicleJourney>
                <VehicleJourneyRef>1055</VehicleJourneyRef>
                <DatedVehicleJourneyRef>1055</DatedVehicleJourneyRef>
                <Operator>
                  <OperatorRef>ANEA</OperatorRef>
                </Operator>
                <LineRef>17B</LineRef>
                <PublishedLineName>17B</PublishedLineName>
                <DirectionRef>Outbound</DirectionRef>
                <Origins>
                  <AffectedStopPoint>
                    <StopPointRef>079073001L</StopPointRef>
                    <StopPointName>Bus Station Stand 12</StopPointName>
                    <StopPointType>busStop</StopPointType>
                  </AffectedStopPoint>
                </Origins>
                <Destinations>
                  <AffectedStopPoint>
                    <StopPointRef>077072001B</StopPointRef>
                    <StopPointName>High Street Stand B</StopPointName>
                    <StopPointType>busStop</StopPointType>
                  </AffectedStopPoint>
                </Destinations>
                <OriginAimedDepartureTime>${currentTime}</OriginAimedDepartureTime>
                <DestinationAimedArrivalTime>${currentTime}</DestinationAimedArrivalTime>
                <Calls>
                  <Call>
                    <StopPointRef>079073001L</StopPointRef>
                    <StopPointName>Bus Station Stand 12</StopPointName>
                    <StopPointType>busStop</StopPointType>
                    <Order>1</Order>
                    <CallCondition>notStopping</CallCondition>
                    <AimedDepartureTime>${currentTime}</AimedDepartureTime>
                    <ExpectedDepartureTime>${currentTime}</ExpectedDepartureTime>
                  </Call>
                </Calls>
              </AffectedVehicleJourney>
            </VehicleJourneys>
          </Affects>
          <Consequences>
            <Consequence>
              <Condition>cancelled</Condition>
            </Consequence>
          </Consequences>
        </PtSituationElement>
      </Situations>
    </SituationExchangeDelivery>
  </ServiceDelivery>
</Siri>`;
