import { getDate } from "@bods-integrated-data/shared/dates";

export const generateMockSiriCancellation = (subscriptionId: string, currentTime: string) => `<?xml version="1.0" encoding="utf-8"?>
<Siri version="2.0" xmlns="http://www.siri.org.uk/siri"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.siri.org.uk/siri http://www.siri.org.uk/schema/2.0/xsd/siri.xsd">
  <ServiceDelivery>
    <ResponseTimestamp>${currentTime}</ResponseTimestamp>
    <ProducerRef>ATB</ProducerRef>
    <Status>true</Status>
    <MoreData>false</MoreData>
    <SituationExchangeDelivery version="2.0">
      <ResponseTimestamp>${currentTime}</ResponseTimestamp>
      <SubscriberRef>${subscriptionId}</SubscriberRef>
      <SubscriptionRef>${subscriptionId}</SubscriptionRef>
      <Status>true</Status>
      <Situations>
        <PtSituationElement>
          <CreationTime>2024-10-09T11:45:00+00:00</CreationTime>
          <ParticipantRef>ATB</ParticipantRef>
          <SituationNumber>123</SituationNumber>
          <Version>2</Version>
          <Source>
            <SourceType>other</SourceType>
          </Source>
          <Progress>closed</Progress>
          <ValidityPeriod>
            <StartTime>${currentTime}</StartTime>
            <EndTime>${getDate(currentTime).add(24, "hours").toISOString()}</EndTime>
          </ValidityPeriod>
          <MiscellaneousReason>roadworks</MiscellaneousReason>
          <Affects>
            <VehicleJourneys>
              <AffectedVehicleJourney>
                <VehicleJourneyRef>2</VehicleJourneyRef>
                <DatedVehicleJourneyRef>2</DatedVehicleJourneyRef>
                <Operator>
                  <OperatorRef>ABCD</OperatorRef>
                </Operator>
                <LineRef>1</LineRef>
                <PublishedLineName>1</PublishedLineName>
                <DirectionRef>Outbound</DirectionRef>
                <Origins>
                  <StopPointRef>01</StopPointRef>
                  <StopPointName>First</StopPointName>
                  <StopPointType>busStop</StopPointType>
                </Origins>
                <Destinations>
                  <StopPointRef>02</StopPointRef>
                  <StopPointName>Second</StopPointName>
                  <StopPointType>busStop</StopPointType>
                </Destinations>
                <Route />
              </AffectedVehicleJourney>
            </VehicleJourneys>
          </Affects>
          <Consequences>
            <Consequence>
              <Condition>cancelled</Condition>
              <Severity>severe</Severity>
            </Consequence>
          </Consequences>
        </PtSituationElement>
        <PtSituationElement>
          <CreationTime>2024-10-09T11:45:00+00:00</CreationTime>
          <ParticipantRef>ATB</ParticipantRef>
          <SituationNumber>124</SituationNumber>
          <Source>
            <SourceType>email</SourceType>
          </Source>
          <Progress>closed</Progress>
          <ValidityPeriod>
            <StartTime>${currentTime}</StartTime>
            <EndTime>${getDate(currentTime).add(24, "hours").toISOString()}</EndTime>
          </ValidityPeriod>
          <MiscellaneousReason>roadworks</MiscellaneousReason>
          <Affects>
            <VehicleJourneys>
              <AffectedVehicleJourney>
                <VehicleJourneyRef>3</VehicleJourneyRef>
                <DatedVehicleJourneyRef>3</DatedVehicleJourneyRef>
                <Operator>
                  <OperatorRef>ABCD</OperatorRef>
                </Operator>
                <LineRef>1</LineRef>
                <PublishedLineName>1</PublishedLineName>
                <DirectionRef>Outbound</DirectionRef>
                <Origins>
                  <StopPointRef>01</StopPointRef>
                  <StopPointName>First</StopPointName>
                  <StopPointType>busStop</StopPointType>
                </Origins>
                <Destinations>
                  <StopPointRef>02</StopPointRef>
                  <StopPointName>Second</StopPointName>
                  <StopPointType>busStop</StopPointType>
                </Destinations>
                <Route />
              </AffectedVehicleJourney>
            </VehicleJourneys>
          </Affects>
          <Consequences>
            <Consequence>
              <Condition>cancelled</Condition>
              <Severity>severe</Severity>
            </Consequence>
          </Consequences>
        </PtSituationElement>
      </Situations>
    </SituationExchangeDelivery>
  </ServiceDelivery>
</Siri>
`;
