import { Database, sql } from "@bods-integrated-data/shared/database";
import { Kysely } from "kysely";

const tables: (keyof Database)[] = ["agency", "calendar_date", "calendar", "frequency", "route", "shape", "stop_time"];

export async function up(db: Kysely<Database>): Promise<void> {
    for (const table of tables) {
        await sql`
            ALTER TABLE ${sql.id(table)}
            ALTER COLUMN id DROP DEFAULT,
            ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY
        `.execute(db);
    }
}

export async function down(db: Kysely<Database>): Promise<void> {
    for (const table of tables) {
        await sql`
        ALTER TABLE ${sql.table(table)}
        ALTER COLUMN id DROP IDENTITY IF EXISTS,
        ADD DEFAULT nextval('${sql.id(table)}_id_seq'::regclass)
    `.execute(db);
    }
}
