import { Database, NewAgency } from "@bods-integrated-data/shared/database";
import { Kysely } from "kysely";

export async function up(db: Kysely<Database>): Promise<void> {
    await db.deleteFrom("agency").execute();
    await db.insertInto("agency").values(agencies).execute();
}

export async function down(): Promise<void> {}

const agencies: NewAgency[] = [
    { id: 2, name: "Cardiff Bus", url: "https://www.traveline.info", phone: "", noc: "CBUS" },
    { id: 3, name: "Adventure Travel", url: "https://www.traveline.info", phone: "", noc: "NADT" },
    { id: 5, name: "Llew Jones Coaches", url: "https://www.traveline.info", phone: "", noc: "LJCO" },
    { id: 6, name: "Arriva Wales", url: "https://www.traveline.info", phone: "", noc: "ACYM" },
    {
        id: 7,
        name: "Monmouthshire County Council",
        url: "https://www.traveline.info",
        phone: "",
        noc: "MNCC",
    },
    { id: 8, name: "Phil Anslow Travel", url: "https://www.traveline.info", phone: "", noc: "ANSL" },
    { id: 9, name: "Thomas of Rhondda", url: "https://www.traveline.info", phone: "", noc: "PRTH" },
    { id: 10, name: "M & H Coaches", url: "https://www.traveline.info", phone: "", noc: "MHCO" },
    { id: 11, name: "Newport Bus", url: "https://www.traveline.info", phone: "", noc: "NWPT" },
    { id: 12, name: "K&P Coaches", url: "https://www.traveline.info", phone: "", noc: "BARB" },
    { id: 13, name: "P & O Lloyd", url: "https://www.traveline.info", phone: "", noc: "PAOL" },
    { id: 14, name: "O R Jones", url: "https://www.traveline.info", phone: "", noc: "OJNS" },
    { id: 15, name: "Morris Travel", url: "https://www.traveline.info", phone: "", noc: "MRRS" },
    { id: 16, name: "First South & West Wales", url: "https://www.traveline.info", phone: "", noc: "FCYM" },
    { id: 17, name: "Stagecoach South Wales", url: "https://www.traveline.info", phone: "", noc: "SSWL" },
    { id: 18, name: "Harris Coaches", url: "https://www.traveline.info", phone: "", noc: "HRRS" },
    { id: 19, name: "Goodsir", url: "https://www.traveline.info", phone: "", noc: "GOOD" },
    { id: 22, name: "Lloyds Coaches", url: "https://www.traveline.info", phone: "", noc: "LLCO" },
    { id: 23, name: "Gwynfor Coaches", url: "https://www.traveline.info", phone: "", noc: "GWCO" },
    { id: 24, name: "Dilwyn's Coaches", url: "https://www.traveline.info", phone: "", noc: "DWYN" },
    { id: 25, name: "Lewis Y Llan", url: "https://www.traveline.info", phone: "", noc: "LLAN" },
    { id: 26, name: "Owen's Travelmaster", url: "https://www.traveline.info", phone: "", noc: "OWNC" },
    {
        id: 27,
        name: "Clynnog & Trefor / Berwyn Coaches",
        url: "https://www.traveline.info",
        phone: "",
        noc: "CTBC",
    },
    {
        id: 28,
        name: "New Bharat Coaches (Southall, London)",
        url: "https://www.traveline.info",
        phone: "",
        noc: "BHAT",
    },
    { id: 30, name: "South Wales Transport", url: "https://www.traveline.info", phone: "", noc: "SWTR" },
    { id: 31, name: "D & G Bus", url: "https://www.traveline.info", phone: "", noc: "DAGC" },
    {
        id: 33,
        name: "Thomas Herbert Jones & Partners",
        url: "https://www.traveline.info",
        phone: "",
        noc: "CAEL",
    },
    { id: 34, name: "Eifion's Coaches", url: "https://www.traveline.info", phone: "", noc: "EFCO" },
    { id: 36, name: "Tanat Valley Coaches", url: "https://www.traveline.info", phone: "", noc: "TANV" },
    {
        id: 37,
        name: "Evans Coaches Tregaron Limited",
        url: "https://www.traveline.info",
        phone: "",
        noc: "JAEV",
    },
    { id: 38, name: "Mid Wales Travel", url: "https://www.traveline.info", phone: "", noc: "MWLM" },
    { id: 40, name: "Arriva Midlands", url: "https://www.traveline.info", phone: "", noc: "AMID" },
    { id: 42, name: "London General", url: "https://www.traveline.info", phone: "", noc: "LGEN" },
    {
        id: 43,
        name: "Road Runner Community Transport",
        url: "https://www.traveline.info",
        phone: "",
        noc: "RRCT",
    },
    {
        id: 44,
        name: "Villager Minibus Sharnbrook",
        url: "https://www.traveline.info",
        phone: "",
        noc: "VILB",
    },
    { id: 45, name: "Ivel Sprinter", url: "https://www.traveline.info", phone: "", noc: "IVEL" },
    { id: 46, name: "Flittabus", url: "https://www.traveline.info", phone: "", noc: "FLTB" },
    { id: 47, name: "Wanderbus", url: "https://www.traveline.info", phone: "", noc: "WWDR" },
    { id: 48, name: "South Beds Dial-a-Ride", url: "https://www.traveline.info", phone: "", noc: "SBDR" },
    { id: 49, name: "Stagecoach Midlands", url: "https://www.traveline.info", phone: "", noc: "SCNH" },
    { id: 50, name: "Arriva Herts and Essex", url: "https://www.traveline.info", phone: "", noc: "ARHE" },
    { id: 51, name: "Ensign Bus", url: "https://www.traveline.info", phone: "", noc: "ENSB" },
    { id: 52, name: "Grant Palmer", url: "https://www.traveline.info", phone: "", noc: "GPLM" },
    { id: 53, name: "Stagecoach London", url: "https://www.traveline.info", phone: "", noc: "ELBG" },
    { id: 55, name: "Stephensons of Essex", url: "https://www.traveline.info", phone: "", noc: "SESX" },
    { id: 56, name: "First Norfolk & Suffolk", url: "https://www.traveline.info", phone: "", noc: "FECS" },
    { id: 57, name: "Konectbus", url: "https://www.traveline.info", phone: "", noc: "KCTB" },
    { id: 58, name: "Arriva Beds and Bucks", url: "https://www.traveline.info", phone: "", noc: "ARBB" },
    { id: 59, name: "Lynx", url: "https://www.traveline.info", phone: "", noc: "LYNX" },
    { id: 60, name: "Sanders Coaches", url: "https://www.traveline.info", phone: "", noc: "SNDR" },
    { id: 62, name: "Coach Services", url: "https://www.traveline.info", phone: "", noc: "CSVC" },
    {
        id: 64,
        name: "Green Line (operated by Arriva)",
        url: "https://www.traveline.info",
        phone: "",
        noc: "GLAR",
    },
    { id: 65, name: "Simonds", url: "https://www.traveline.info", phone: "", noc: "SIMO" },
    { id: 66, name: "H Semmence & Co.", url: "https://www.traveline.info", phone: "", noc: "SEMM" },
    { id: 67, name: "Go To Town", url: "https://www.traveline.info", phone: "", noc: "WNCT" },
    { id: 68, name: "Centrebus", url: "https://www.traveline.info", phone: "", noc: "CBBH" },
    { id: 71, name: "Redline", url: "https://www.traveline.info", phone: "", noc: "RLNE" },
    { id: 72, name: "Vale Travel", url: "https://www.traveline.info", phone: "", noc: "VLET" },
    { id: 73, name: "Z & S Transport", url: "https://www.traveline.info", phone: "", noc: "ZSIN" },
    {
        id: 76,
        name: "West Berkshire Council Transport Services",
        url: "https://www.traveline.info",
        phone: "",
        noc: "WBCT",
    },
    { id: 77, name: "Newbury & District", url: "https://www.traveline.info", phone: "", noc: "NADS" },
    { id: 78, name: "Reading Buses", url: "https://www.traveline.info", phone: "", noc: "RBUS" },
    { id: 83, name: "Stagecoach Oxfordshire", url: "https://www.traveline.info", phone: "", noc: "SCOX" },
    { id: 84, name: "Hornsbys Bus & Coach", url: "https://www.traveline.info", phone: "", noc: "HNTS" },
    { id: 85, name: "Berwyn", url: "https://www.traveline.info", phone: "", noc: "BERW" },
    { id: 87, name: "Celtic Travel", url: "https://www.traveline.info", phone: "", noc: "CELT" },
    { id: 90, name: "Diamond Bus", url: "https://www.traveline.info", phone: "", noc: "DIAM" },
    { id: 91, name: "Air-Rail Link", url: "https://www.traveline.info", phone: "", noc: "BHXL" },
    { id: 92, name: "West Midlands Metro", url: "https://www.traveline.info", phone: "", noc: "MDMT" },
    { id: 93, name: "Thandi Red Limited", url: "https://www.traveline.info", phone: "", noc: "EVGC" },
    { id: 94, name: "First Worcestershire", url: "https://www.traveline.info", phone: "", noc: "FSMR" },
    { id: 95, name: "Flexibus", url: "https://www.traveline.info", phone: "", noc: "AMGR" },
    { id: 97, name: "Kevs Cars and Coaches", url: "https://www.traveline.info", phone: "", noc: "KEVS" },
    {
        id: 99,
        name: "National Express West Midlands",
        url: "https://www.traveline.info",
        phone: "",
        noc: "TNXB",
    },
    { id: 101, name: "Select Bus Services", url: "https://www.traveline.info", phone: "", noc: "SLBS" },
    { id: 102, name: "LandFlight", url: "https://www.traveline.info", phone: "", noc: "SLVL" },
    { id: 103, name: "National Express Coventry", url: "https://www.traveline.info", phone: "", noc: "TCVW" },
    { id: 104, name: "Let's Go", url: "https://www.traveline.info", phone: "", noc: "TEXP" },
    {
        id: 105,
        name: "Walsall Community Transport",
        url: "https://www.traveline.info",
        phone: "",
        noc: "WACT",
    },
    { id: 108, name: "Arriva Midlands", url: "https://www.traveline.info", phone: "", noc: "AMNO" },
    { id: 109, name: "Banga Buses", url: "https://www.traveline.info", phone: "", noc: "BANG" },
    {
        id: 110,
        name: "Caerphilly County Borough Council",
        url: "https://www.traveline.info",
        phone: "",
        noc: "CON2",
    },
    { id: 111, name: "Crickhowell Taxis", url: "https://www.traveline.info", phone: "", noc: "CRTX" },
    { id: 112, name: "DANSA", url: "https://www.traveline.info", phone: "", noc: "DVPA" },
    { id: 113, name: "Denbighshire Council", url: "https://www.traveline.info", phone: "", noc: "DNBG" },
    { id: 114, name: "C G Myall & Son", url: "https://www.traveline.info", phone: "", noc: "MYAL" },
    { id: 116, name: "A2B Bus and Coach", url: "https://www.traveline.info", phone: "", noc: "A2BR" },
    { id: 117, name: "Lord's Travel", url: "https://www.traveline.info", phone: "", noc: "LTEA" },
    { id: 118, name: "Stagecoach East", url: "https://www.traveline.info", phone: "", noc: "SCCM" },
    { id: 119, name: "Dews Coaches", url: "https://www.traveline.info", phone: "", noc: "DEWS" },
    { id: 123, name: "Whippet Coaches", url: "https://www.traveline.info", phone: "", noc: "WHIP" },
    {
        id: 124,
        name: "Fenland Association for Community Transport",
        url: "https://www.traveline.info",
        phone: "",
        noc: "FACT",
    },
    {
        id: 125,
        name: "Ramsey and District Community Bus Association",
        url: "https://www.traveline.info",
        phone: "",
        noc: "RADC",
    },
    { id: 128, name: "Edwards Coaches", url: "https://www.traveline.info", phone: "", noc: "EDWC" },
    { id: 129, name: "Andrews of Tideswell", url: "https://www.traveline.info", phone: "", noc: "ANTR" },
    { id: 130, name: "Hulleys of Baslow", url: "https://www.traveline.info", phone: "", noc: "HULS" },
    { id: 131, name: "Notts and Derby", url: "https://www.traveline.info", phone: "", noc: "NDTR" },
    { id: 132, name: "High Peak", url: "https://www.traveline.info", phone: "", noc: "HIPK" },
    { id: 133, name: "Ashley Travel", url: "https://www.traveline.info", phone: "", noc: "ASHL" },
    { id: 134, name: "Johnson Brothers", url: "https://www.traveline.info", phone: "", noc: "JBTL" },
    { id: 135, name: "Diamond Bus East Midlands", url: "https://www.traveline.info", phone: "", noc: "MDCL" },
    { id: 138, name: "Littles Travel", url: "https://www.traveline.info", phone: "", noc: "ltls" },
    { id: 139, name: "TM Travel", url: "https://www.traveline.info", phone: "", noc: "TMTL" },
    { id: 140, name: "CT4N", url: "https://www.traveline.info", phone: "", noc: "NOCT" },
    { id: 143, name: "trentbarton", url: "https://www.traveline.info", phone: "", noc: "TBTN" },
    { id: 145, name: "Harpurs Coaches", url: "https://www.traveline.info", phone: "", noc: "HASO" },
    { id: 146, name: "Viking Coaches", url: "https://www.traveline.info", phone: "", noc: "WVIK" },
    { id: 147, name: "Hawkes Coaches", url: "https://www.traveline.info", phone: "", noc: "HWKS" },
    { id: 148, name: "Bagnalls", url: "https://www.traveline.info", phone: "", noc: "BAGN" },
    { id: 149, name: "Stagecoach Manchester", url: "https://www.traveline.info", phone: "", noc: "SCMN" },
    { id: 152, name: "Stagecoach Yorkshire", url: "https://www.traveline.info", phone: "", noc: "SYRK" },
    { id: 153, name: "First South Yorkshire", url: "https://www.traveline.info", phone: "", noc: "FSYO" },
    { id: 154, name: "Glovers", url: "https://www.traveline.info", phone: "", noc: "GLOV" },
    { id: 156, name: "Stotts Tours", url: "https://www.traveline.info", phone: "", noc: "STOT" },
    {
        id: 157,
        name: "South Pennine Community Transport",
        url: "https://www.traveline.info",
        phone: "",
        noc: "SPCT",
    },
    {
        id: 162,
        name: "Ashbourne Community Transport",
        url: "https://www.traveline.info",
        phone: "",
        noc: "ASCT",
    },
    { id: 163, name: "Centrebus", url: "https://www.traveline.info", phone: "", noc: "CBNL" },
    { id: 164, name: "Roberts Coaches", url: "https://www.traveline.info", phone: "", noc: "RBTS" },
    { id: 165, name: "Kinchbus", url: "https://www.traveline.info", phone: "", noc: "KBUS" },
    { id: 167, name: "First Leicester", url: "https://www.traveline.info", phone: "", noc: "FLEI" },
    { id: 171, name: "CallConnect", url: "https://www.traveline.info", phone: "", noc: "CALC" },
    { id: 172, name: "Delaine Buses", url: "https://www.traveline.info", phone: "", noc: "DELA" },
    { id: 173, name: "Brylaine Travel", url: "https://www.traveline.info", phone: "", noc: "BRYL" },
    { id: 174, name: "Hunts Coaches", url: "https://www.traveline.info", phone: "", noc: "HNTC" },
    { id: 175, name: "PC Coaches", url: "https://www.traveline.info", phone: "", noc: "PCCO" },
    { id: 176, name: "Sleafordian Coaches", url: "https://www.traveline.info", phone: "", noc: "SLEA" },
    { id: 177, name: "Haines Coaches", url: "https://www.traveline.info", phone: "", noc: "HAIN" },
    { id: 178, name: "Grayscroft Coaches", url: "https://www.traveline.info", phone: "", noc: "GRYC" },
    { id: 180, name: "J R Dent Coaches", url: "https://www.traveline.info", phone: "", noc: "DENN" },
    { id: 181, name: "Bland's", url: "https://www.traveline.info", phone: "", noc: "MBTR" },
    {
        id: 182,
        name: "Marshalls of Sutton on Trent",
        url: "https://www.traveline.info",
        phone: "",
        noc: "MSOT",
    },
    { id: 183, name: "Fowlers Travel", url: "https://www.traveline.info", phone: "", noc: "FOWT" },
    { id: 186, name: "Gem Mini Travel", url: "https://www.traveline.info", phone: "", noc: "GMMN" },
    { id: 187, name: "Vectare", url: "https://www.traveline.info", phone: "", noc: "VECT" },
    { id: 188, name: "A C Williams", url: "https://www.traveline.info", phone: "", noc: "WMSA" },
    { id: 192, name: "East Yorkshire", url: "https://www.traveline.info", phone: "", noc: "EYMS" },
    { id: 195, name: "Britannia Bus", url: "https://www.traveline.info", phone: "", noc: "BTNA" },
    {
        id: 198,
        name: "Cogenhoe and Whiston Parish Council",
        url: "https://www.traveline.info",
        phone: "",
        noc: "CWPC",
    },
    { id: 199, name: "Nottingham City Transport", url: "https://www.traveline.info", phone: "", noc: "NCTR" },
    {
        id: 200,
        name: "Nottingham Express Transit (Tram)",
        url: "https://www.traveline.info",
        phone: "",
        noc: "NEXT",
    },
    { id: 201, name: "Our Centre", url: "https://www.traveline.info", phone: "", noc: "OCNT" },
    {
        id: 202,
        name: "Nottinghamshire County Council Fleet Services",
        url: "https://www.traveline.info",
        phone: "",
        noc: "NOTB",
    },
    { id: 203, name: "Soar Valley Community Bus", url: "https://www.traveline.info", phone: "", noc: "SVCB" },
    { id: 204, name: "Sharpes of Nottingham", url: "https://www.traveline.info", phone: "", noc: "SHRN" },
    {
        id: 205,
        name: "Ravenshead Community Project",
        url: "https://www.traveline.info",
        phone: "",
        noc: "RHCP",
    },
    { id: 207, name: "Nottingham Minibus", url: "https://www.traveline.info", phone: "", noc: "PRVN" },
    { id: 212, name: "Borders Buses", url: "https://www.traveline.info", phone: "", noc: "BORD" },
    { id: 213, name: "Go North East", url: "https://www.traveline.info", phone: "", noc: "GNEL" },
    { id: 216, name: "Arriva North East", url: "https://www.traveline.info", phone: "", noc: "ANUM" },
    { id: 217, name: "Peter Hogg of Jedburgh", url: "https://www.traveline.info", phone: "", noc: "HOGG" },
    { id: 220, name: "Stagecoach North East", url: "https://www.traveline.info", phone: "", noc: "SCNE" },
    { id: 222, name: "Telfords Coaches", url: "https://www.traveline.info", phone: "", noc: "TELF" },
    { id: 223, name: "Travelsure", url: "https://www.traveline.info", phone: "", noc: "TSCL" },
    {
        id: 224,
        name: "Upper Coquetdale Community Transport",
        url: "https://www.traveline.info",
        phone: "",
        noc: "UCCT",
    },
    { id: 225, name: "Wright Brothers Coaches", url: "https://www.traveline.info", phone: "", noc: "WGTB" },
    { id: 229, name: "Arriva North East", url: "https://www.traveline.info", phone: "", noc: "ANEA" },
    { id: 230, name: "Generation Travel", url: "https://www.traveline.info", phone: "", noc: "GTLT" },
    { id: 231, name: "Hodgsons", url: "https://www.traveline.info", phone: "", noc: "HDGS" },
    { id: 232, name: "Paul's Travel", url: "https://www.traveline.info", phone: "", noc: "PTRA" },
    { id: 236, name: "A-line Coaches", url: "https://www.traveline.info", phone: "", noc: "ALCG" },
    { id: 237, name: "Gateshead Central Taxis", url: "https://www.traveline.info", phone: "", noc: "GHCT" },
    { id: 239, name: "Nexus Ferry", url: "https://www.traveline.info", phone: "", noc: "NXSF" },
    { id: 240, name: "JH Coaches", url: "https://www.traveline.info", phone: "", noc: "JHCL" },
    { id: 241, name: "Tyne and Wear Metro", url: "https://www.traveline.info", phone: "", noc: "NXMT" },
    { id: 242, name: "Station Taxis", url: "https://www.traveline.info", phone: "", noc: "STNX" },
    { id: 243, name: "Weardale Motor Services", url: "https://www.traveline.info", phone: "", noc: "WMSV" },
    { id: 245, name: "The Little White Bus", url: "https://www.traveline.info", phone: "", noc: "UWCO" },
    { id: 246, name: "Ferryhill Village Travel", url: "https://www.traveline.info", phone: "", noc: "FVTL" },
    { id: 247, name: "Stanley Travel", url: "https://www.traveline.info", phone: "", noc: "STNE" },
    { id: 249, name: "Cumbria Classic Coaches", url: "https://www.traveline.info", phone: "", noc: "CUCC" },
    { id: 250, name: "Nefyn", url: "https://www.traveline.info", phone: "", noc: "NFYN" },
    { id: 251, name: "Arriva North West", url: "https://www.traveline.info", phone: "", noc: "ANWE" },
    { id: 252, name: "Aimee's", url: "https://www.traveline.info", phone: "", noc: "TXCO" },
    { id: 253, name: "Hollinshead Coaches", url: "https://www.traveline.info", phone: "", noc: "HOLL" },
    { id: 254, name: "Mikro Coaches", url: "https://www.traveline.info", phone: "", noc: "MIKO" },
    { id: 255, name: "Warrington's Own Buses", url: "https://www.traveline.info", phone: "", noc: "WBTR" },
    { id: 256, name: "A2B Travel", url: "https://www.traveline.info", phone: "", noc: "A2BV" },
    { id: 257, name: "Aintree Coachlines", url: "https://www.traveline.info", phone: "", noc: "AINT" },
    { id: 258, name: "Arriva North West", url: "https://www.traveline.info", phone: "", noc: "AMSY" },
    {
        id: 260,
        name: "Stagecoach Merseyside and South Lancashire",
        url: "https://www.traveline.info",
        phone: "",
        noc: "SCMY",
    },
    { id: 261, name: "Blueworks Private Hire", url: "https://www.traveline.info", phone: "", noc: "BPHI" },
    { id: 262, name: "Border Rambler", url: "https://www.traveline.info", phone: "", noc: "BRCS" },
    { id: 263, name: "Ellenvale Coaches", url: "https://www.traveline.info", phone: "", noc: "ELNV" },
    { id: 264, name: "Fellrunner", url: "https://www.traveline.info", phone: "", noc: "FELL" },
    { id: 265, name: "Houston's Minicoaches", url: "https://www.traveline.info", phone: "", noc: "HNMI" },
    { id: 268, name: "Kirkby Lonsdale Coaches", url: "https://www.traveline.info", phone: "", noc: "KLCO" },
    { id: 269, name: "Lakeland Coaches", url: "https://www.traveline.info", phone: "", noc: "LCAC" },
    {
        id: 270,
        name: "Mountain Goat Holidays and Tours",
        url: "https://www.traveline.info",
        phone: "",
        noc: "MTGT",
    },
    { id: 271, name: "NBM Hire Ltd", url: "https://www.traveline.info", phone: "", noc: "NBMH" },
    { id: 272, name: "Reays Coaches", url: "https://www.traveline.info", phone: "", noc: "REAY" },
    {
        id: 275,
        name: "Western Dales Community Bus",
        url: "https://www.traveline.info",
        phone: "",
        noc: "WDCB",
    },
    { id: 278, name: "The Burnley Bus Company", url: "https://www.traveline.info", phone: "", noc: "BPTR" },
    { id: 279, name: "Cumfybus", url: "https://www.traveline.info", phone: "", noc: "CUBU" },
    { id: 280, name: "First Greater Manchester", url: "https://www.traveline.info", phone: "", noc: "FMAN" },
    {
        id: 281,
        name: "First Halifax, Calder Valley & Huddersfield",
        url: "https://www.traveline.info",
        phone: "",
        noc: "FHUD",
    },
    { id: 283, name: "Little Gem", url: "https://www.traveline.info", phone: "", noc: "GOGO" },
    { id: 285, name: "Diamond Bus North West", url: "https://www.traveline.info", phone: "", noc: "GTRI" },
    { id: 286, name: "Hattons Travel", url: "https://www.traveline.info", phone: "", noc: "HATT" },
    { id: 287, name: "Huyton Travel", url: "https://www.traveline.info", phone: "", noc: "HUYT" },
    { id: 288, name: "Metrolink", url: "https://www.traveline.info", phone: "", noc: "METL" },
    { id: 289, name: "Olympia Travel", url: "https://www.traveline.info", phone: "", noc: "OLYM" },
    { id: 290, name: "Nexus Move", url: "https://www.traveline.info", phone: "", noc: "RDCA" },
    { id: 291, name: "Rosso", url: "https://www.traveline.info", phone: "", noc: "ROST" },
    { id: 292, name: "Tyrers Coaches", url: "https://www.traveline.info", phone: "", noc: "RSTY" },
    { id: 293, name: "Travel Assist", url: "https://www.traveline.info", phone: "", noc: "TASL" },
    { id: 294, name: "Vision Bus", url: "https://www.traveline.info", phone: "", noc: "VISB" },
    { id: 297, name: "A1 Coaches", url: "https://www.traveline.info", phone: "", noc: "AOLC" },
    { id: 298, name: "Archway Travel", url: "https://www.traveline.info", phone: "", noc: "ARCT" },
    { id: 299, name: "Avacab", url: "https://www.traveline.info", phone: "", noc: "AVAC" },
    {
        id: 300,
        name: "Bretherton Gold Line Tours",
        url: "https://www.traveline.info",
        phone: "",
        noc: "BGLT",
    },
    { id: 301, name: "B & J Travel", url: "https://www.traveline.info", phone: "", noc: "BJTR" },
    { id: 302, name: "Blackpool Transport", url: "https://www.traveline.info", phone: "", noc: "BLAC" },
    { id: 303, name: "Blackpool Coach Hire", url: "https://www.traveline.info", phone: "", noc: "BLCK" },
    { id: 304, name: "Blackburn Private Hire", url: "https://www.traveline.info", phone: "", noc: "BLPH" },
    {
        id: 306,
        name: "Coach Hire Executive Travel Ltd",
        url: "https://www.traveline.info",
        phone: "",
        noc: "BVTE",
    },
    { id: 307, name: "Charlton Mini's", url: "https://www.traveline.info", phone: "", noc: "CHAR" },
    { id: 308, name: "Coastal Coaches", url: "https://www.traveline.info", phone: "", noc: "COAS" },
    { id: 309, name: "Cranberry Coachways", url: "https://www.traveline.info", phone: "", noc: "CRAN" },
    { id: 310, name: "Don Fraser Coaches", url: "https://www.traveline.info", phone: "", noc: "DONF" },
    { id: 311, name: "Englands Limousines", url: "https://www.traveline.info", phone: "", noc: "ENLI" },
    { id: 312, name: "Express Travel", url: "https://www.traveline.info", phone: "", noc: "ETNW" },
    { id: 313, name: "Finches", url: "https://www.traveline.info", phone: "", noc: "FCHS" },
    { id: 314, name: "Foreign Support", url: "https://www.traveline.info", phone: "", noc: "FSNW" },
    { id: 316, name: "Hodsons Coaches", url: "https://www.traveline.info", phone: "", noc: "HODG" },
    { id: 317, name: "Holmeswood Coaches Ltd", url: "https://www.traveline.info", phone: "", noc: "HWCO" },
    { id: 318, name: "The Keighley Bus Company", url: "https://www.traveline.info", phone: "", noc: "KDTR" },
    { id: 321, name: "The Blackburn Bus Company", url: "https://www.traveline.info", phone: "", noc: "LNUD" },
    { id: 322, name: "Mario Coaches", url: "https://www.traveline.info", phone: "", noc: "MARI" },
    { id: 323, name: "Moving People", url: "https://www.traveline.info", phone: "", noc: "MOVP" },
    { id: 325, name: "Coastliner Buses", url: "https://www.traveline.info", phone: "", noc: "NUTT" },
    { id: 326, name: "Pilkingtonbus", url: "https://www.traveline.info", phone: "", noc: "NWBT" },
    { id: 327, name: "JP Travel", url: "https://www.traveline.info", phone: "", noc: "PBHJ" },
    { id: 328, name: "Preston Bus", url: "https://www.traveline.info", phone: "", noc: "PBLT" },
    { id: 329, name: "Peoples Bus", url: "https://www.traveline.info", phone: "", noc: "PPBU" },
    { id: 330, name: "P & S Nelson", url: "https://www.traveline.info", phone: "", noc: "PSNL" },
    { id: 331, name: "Redline Travel", url: "https://www.traveline.info", phone: "", noc: "REDL" },
    { id: 332, name: "Saunders of Preston", url: "https://www.traveline.info", phone: "", noc: "SAUN" },
    { id: 333, name: "Shane Nuttall", url: "https://www.traveline.info", phone: "", noc: "SNCH" },
    { id: 335, name: "Waltons Coach Hire", url: "https://www.traveline.info", phone: "", noc: "WCHL" },
    { id: 336, name: "Wyre Coaches", url: "https://www.traveline.info", phone: "", noc: "WCOA" },
    { id: 337, name: "Pendle Coaches", url: "https://www.traveline.info", phone: "", noc: "ZOCO" },
    { id: 338, name: "A and J Taxis", url: "https://www.traveline.info", phone: "", noc: "AJTX" },
    { id: 339, name: "Al's Coaches", url: "https://www.traveline.info", phone: "", noc: "ALSC" },
    { id: 340, name: "Derek Hilton Travel", url: "https://www.traveline.info", phone: "", noc: "HILT" },
    { id: 341, name: "Maghull Coaches", url: "https://www.traveline.info", phone: "", noc: "MAGH" },
    { id: 343, name: "Anthony's Travel", url: "https://www.traveline.info", phone: "", noc: "ANTT" },
    { id: 344, name: "Selwyn's Travel", url: "https://www.traveline.info", phone: "", noc: "SELT" },
    { id: 346, name: "Ashcroft Travel", url: "https://www.traveline.info", phone: "", noc: "ASHT" },
    { id: 348, name: "Howards Travel", url: "https://www.traveline.info", phone: "", noc: "HOWT" },
    { id: 349, name: "Liverpool City Sights", url: "https://www.traveline.info", phone: "", noc: "LCIS" },
    {
        id: 351,
        name: "Oswestry Community Action (Qube)",
        url: "https://www.traveline.info",
        phone: "",
        noc: "OCAC",
    },
    { id: 353, name: "Pat's Coaches", url: "https://www.traveline.info", phone: "", noc: "PATS" },
    {
        id: 354,
        name: "Pembrokeshire County Council",
        url: "https://www.traveline.info",
        phone: "",
        noc: "PEMB",
    },
    { id: 355, name: "Peter's Minibus Hire", url: "https://www.traveline.info", phone: "", noc: "PCMH" },
    { id: 356, name: "Peyton Travel", url: "https://www.traveline.info", phone: "", noc: "PTLW" },
    { id: 357, name: "Richards Bros", url: "https://www.traveline.info", phone: "", noc: "RBRO" },
    { id: 358, name: "Ridgways", url: "https://www.traveline.info", phone: "", noc: "RDWY" },
    { id: 359, name: "Sarah Bell", url: "https://www.traveline.info", phone: "", noc: "SABE" },
    { id: 360, name: "Sargeants Brothers", url: "https://www.traveline.info", phone: "", noc: "SARG" },
    { id: 361, name: "Select Coaches", url: "https://www.traveline.info", phone: "", noc: "SELB" },
    { id: 362, name: "Red Rose Travel", url: "https://www.traveline.info", phone: "", noc: "RRTR" },
    { id: 363, name: "Carousel Buses", url: "https://www.traveline.info", phone: "", noc: "CSLB" },
    { id: 364, name: "Thames Valley Buses", url: "https://www.traveline.info", phone: "", noc: "CTNY" },
    {
        id: 365,
        name: "First Berkshire & The Thames Valley",
        url: "https://www.traveline.info",
        phone: "",
        noc: "FTVA",
    },
    { id: 366, name: "Langston & Tasker", url: "https://www.traveline.info", phone: "", noc: "LTKR" },
    { id: 367, name: "Red Eagle", url: "https://www.traveline.info", phone: "", noc: "REDE" },
    { id: 368, name: "Star Travel", url: "https://www.traveline.info", phone: "", noc: "STAR" },
    { id: 369, name: "White Bus Services", url: "https://www.traveline.info", phone: "", noc: "WBSV" },
    { id: 370, name: "Metroline Travel", url: "https://www.traveline.info", phone: "", noc: "MTLN" },
    {
        id: 372,
        name: "Winslow & District Community Bus",
        url: "https://www.traveline.info",
        phone: "",
        noc: "WINS",
    },
    {
        id: 375,
        name: "Risborough Area Community Bus",
        url: "https://www.traveline.info",
        phone: "",
        noc: "RACB",
    },
    { id: 376, name: "Oxford Bus Company", url: "https://www.traveline.info", phone: "", noc: "OXBC" },
    { id: 377, name: "Thames Travel", url: "https://www.traveline.info", phone: "", noc: "THTR" },
    { id: 378, name: "Going Forward Buses", url: "https://www.traveline.info", phone: "", noc: "GFWD" },
    { id: 379, name: "Whites Coaches", url: "https://www.traveline.info", phone: "", noc: "WHTS" },
    { id: 380, name: "OurBus Bartons", url: "https://www.traveline.info", phone: "", noc: "OURB" },
    {
        id: 381,
        name: "West Oxfordshire Community Transport",
        url: "https://www.traveline.info",
        phone: "",
        noc: "WOCT",
    },
    { id: 382, name: "Grayline Coaches", url: "https://www.traveline.info", phone: "", noc: "GYLC" },
    { id: 383, name: "Diamond Bus South East", url: "https://www.traveline.info", phone: "", noc: "WNGS" },
    { id: 384, name: "Shipston Link", url: "https://www.traveline.info", phone: "", noc: "SHPL" },
    { id: 385, name: "Faringdon Community Bus", url: "https://www.traveline.info", phone: "", noc: "FGDN" },
    {
        id: 387,
        name: "Kidlington Assisted Transport CIC",
        url: "https://www.traveline.info",
        phone: "",
        noc: "KAST",
    },
    {
        id: 389,
        name: "Richard Wellesley Memorial Community Minibus",
        url: "https://www.traveline.info",
        phone: "",
        noc: "RWMC",
    },
    {
        id: 390,
        name: "Villager Community Bus (Oxon)",
        url: "https://www.traveline.info",
        phone: "",
        noc: "VCBO",
    },
    { id: 391, name: "Pulhams Coaches", url: "https://www.traveline.info", phone: "", noc: "PULH" },
    { id: 393, name: "First Essex", url: "https://www.traveline.info", phone: "", noc: "FESX" },
    { id: 394, name: "NIBSbuses", url: "https://www.traveline.info", phone: "", noc: "NIBS" },
    { id: 395, name: "Arrow Taxi", url: "https://www.traveline.info", phone: "", noc: "ARWT" },
    { id: 396, name: "Panther Travel", url: "https://www.traveline.info", phone: "", noc: "PNTR" },
    { id: 397, name: "Ipswich Buses", url: "https://www.traveline.info", phone: "", noc: "IPSW" },
    { id: 398, name: "Hedingham & Chambers", url: "https://www.traveline.info", phone: "", noc: "HEDO" },
    {
        id: 399,
        name: "Epping Forest Community Transport",
        url: "https://www.traveline.info",
        phone: "",
        noc: "EFCT",
    },
    { id: 401, name: "Arriva London North", url: "https://www.traveline.info", phone: "", noc: "ALNO" },
    { id: 402, name: "JW Lodge & Sons", url: "https://www.traveline.info", phone: "", noc: "LODG" },
    { id: 405, name: "Essex & Suffolk DaRT", url: "https://www.traveline.info", phone: "", noc: "EASD" },
    { id: 406, name: "Go Ahead London", url: "https://www.traveline.info", phone: "", noc: "GAHL" },
    { id: 407, name: "Hedingham & Chambers", url: "https://www.traveline.info", phone: "", noc: "CHAM" },
    {
        id: 408,
        name: "Brightlingsea Ferry Services",
        url: "https://www.traveline.info",
        phone: "",
        noc: "BLSF",
    },
    { id: 409, name: "Burnham Ferry", url: "https://www.traveline.info", phone: "", noc: "BURN" },
    { id: 410, name: "Compass Travel", url: "https://www.traveline.info", phone: "", noc: "COMT" },
    { id: 412, name: "Metrobus", url: "https://www.traveline.info", phone: "", noc: "METR" },
    { id: 413, name: "Arriva Kent and Surrey", url: "https://www.traveline.info", phone: "", noc: "AKSS" },
    { id: 414, name: "Stagecoach South East", url: "https://www.traveline.info", phone: "", noc: "SCEK" },
    { id: 416, name: "1st Bus Stop Ltd", url: "https://www.traveline.info", phone: "", noc: "FBSM" },
    { id: 417, name: "Kent Coach Tours", url: "https://www.traveline.info", phone: "", noc: "KCTR" },
    { id: 418, name: "London United", url: "https://www.traveline.info", phone: "", noc: "LUTD" },
    { id: 419, name: "Bexhill Community Bus", url: "https://www.traveline.info", phone: "", noc: "BEXB" },
    { id: 420, name: "Cuckmere Buses", url: "https://www.traveline.info", phone: "", noc: "CKMR" },
    { id: 421, name: "Nu-Venture", url: "https://www.traveline.info", phone: "", noc: "NVTR" },
    {
        id: 422,
        name: "Brighton & Hove Bus and Coach Company",
        url: "https://www.traveline.info",
        phone: "",
        noc: "BHBC",
    },
    {
        id: 423,
        name: "Community Transport for Lewes Area",
        url: "https://www.traveline.info",
        phone: "",
        noc: "CTLW",
    },
    { id: 424, name: "ASD Coaches", url: "https://www.traveline.info", phone: "", noc: "ASDC" },
    { id: 425, name: "Seaford & District", url: "https://www.traveline.info", phone: "", noc: "SEAD" },
    { id: 426, name: "Arriva London South", url: "https://www.traveline.info", phone: "", noc: "ALSO" },
    { id: 427, name: "The Big Lemon", url: "https://www.traveline.info", phone: "", noc: "LEMN" },
    { id: 431, name: "Hams Travel", url: "https://www.traveline.info", phone: "", noc: "HAMS" },
    {
        id: 432,
        name: "Handcross District Community Bus",
        url: "https://www.traveline.info",
        phone: "",
        noc: "HDBC",
    },
    { id: 433, name: "Go-Coach Hire", url: "https://www.traveline.info", phone: "", noc: "GOCH" },
    { id: 434, name: "Selsey Community Bus", url: "https://www.traveline.info", phone: "", noc: "SLCS" },
    {
        id: 435,
        name: "Autocar Bus & Coach Services",
        url: "https://www.traveline.info",
        phone: "",
        noc: "AUTO",
    },
    { id: 436, name: "Starline", url: "https://www.traveline.info", phone: "", noc: "SLNE" },
    { id: 437, name: "Redroute Buses", url: "https://www.traveline.info", phone: "", noc: "RDRT" },
    {
        id: 438,
        name: "Wealdlink Community Transport",
        url: "https://www.traveline.info",
        phone: "",
        noc: "NWCT",
    },
    { id: 439, name: "Buses4U", url: "https://www.traveline.info", phone: "", noc: "BS4U" },
    { id: 441, name: "Emsworth & District", url: "https://www.traveline.info", phone: "", noc: "EDMS" },
    { id: 442, name: "Falcon Coaches", url: "https://www.traveline.info", phone: "", noc: "FALC" },
    { id: 443, name: "Abellio London", url: "https://www.traveline.info", phone: "", noc: "ABLO" },
    { id: 444, name: "Quality Line", url: "https://www.traveline.info", phone: "", noc: "QULN" },
    { id: 445, name: "Rambler Coaches", url: "https://www.traveline.info", phone: "", noc: "RAMB" },
    { id: 446, name: "Bear Buses", url: "https://www.traveline.info", phone: "", noc: "BEAR" },
    { id: 447, name: "Arriva Kent and Surrey", url: "https://www.traveline.info", phone: "", noc: "AMTM" },
    { id: 448, name: "Cruisers", url: "https://www.traveline.info", phone: "", noc: "MINI" },
    {
        id: 449,
        name: "Chalkwell Garage & Coach Hire",
        url: "https://www.traveline.info",
        phone: "",
        noc: "CHLK",
    },
    { id: 450, name: "Rye Community Transport", url: "https://www.traveline.info", phone: "", noc: "RYEC" },
    { id: 451, name: "Regent Coaches", url: "https://www.traveline.info", phone: "", noc: "RGNT" },
    { id: 452, name: "Travelmasters", url: "https://www.traveline.info", phone: "", noc: "TMST" },
    { id: 454, name: "Safeguard Buses", url: "https://www.traveline.info", phone: "", noc: "SFGC" },
    { id: 455, name: "Carlone Buses", url: "https://www.traveline.info", phone: "", noc: "CLNB" },
    { id: 458, name: "Reptons Coaches", url: "https://www.traveline.info", phone: "", noc: "REPT" },
    { id: 459, name: "Brookline", url: "https://www.traveline.info", phone: "", noc: "BRLN" },
    { id: 460, name: "Sussex Coaches", url: "https://www.traveline.info", phone: "", noc: "SUSC" },
    { id: 461, name: "Cardinal Buses", url: "https://www.traveline.info", phone: "", noc: "CARD" },
    { id: 463, name: "Redwing Coaches", url: "https://www.traveline.info", phone: "", noc: "REDC" },
    { id: 464, name: "Clarkes of London", url: "https://www.traveline.info", phone: "", noc: "CLKL" },
    { id: 465, name: "Centaur Coaches", url: "https://www.traveline.info", phone: "", noc: "CNTC" },
    { id: 466, name: "Edward Thomas", url: "https://www.traveline.info", phone: "", noc: "EDTM" },
    { id: 467, name: "Sullivan Buses", url: "https://www.traveline.info", phone: "", noc: "SULV" },
    { id: 468, name: "Crosskeys Coaches", url: "https://www.traveline.info", phone: "", noc: "CRKC" },
    { id: 470, name: "Harting Minibus CIC", url: "https://www.traveline.info", phone: "", noc: "HMIN" },
    { id: 471, name: "Brian Jones Coaches", url: "https://www.traveline.info", phone: "", noc: "BJCO" },
    { id: 472, name: "Compaid Trust", url: "https://www.traveline.info", phone: "", noc: "CPDT" },
    {
        id: 474,
        name: "Romney Hythe & Dymchurch Light Railway",
        url: "https://www.traveline.info",
        phone: "",
        noc: "RHDR",
    },
    { id: 476, name: "R & J Coaches", url: "https://www.traveline.info", phone: "", noc: "RJCO" },
    {
        id: 477,
        name: "Gatwick Airport inter-terminal Shuttle",
        url: "https://www.traveline.info",
        phone: "",
        noc: "BAAG",
    },
    { id: 478, name: "United Minibuses", url: "https://www.traveline.info", phone: "", noc: "UNTM" },
    { id: 479, name: "Nauticalia Ferry", url: "https://www.traveline.info", phone: "", noc: "NAUT" },
    { id: 483, name: "Midhurst Community Bus", url: "https://www.traveline.info", phone: "", noc: "MDCM" },
    { id: 484, name: "London Sovereign", url: "https://www.traveline.info", phone: "", noc: "LSOV" },
    { id: 485, name: "Richmonds Coaches", url: "https://www.traveline.info", phone: "", noc: "RCHC" },
    { id: 487, name: "Lucketts of Watford", url: "https://www.traveline.info", phone: "", noc: "LUCW" },
    { id: 488, name: "Landmark Coaches", url: "https://www.traveline.info", phone: "", noc: "LDMK" },
    {
        id: 491,
        name: "Bishops Stortford Community Transport",
        url: "https://www.traveline.info",
        phone: "",
        noc: "BSCT",
    },
    { id: 492, name: "SP Cars", url: "https://www.traveline.info", phone: "", noc: "SCAR" },
    {
        id: 495,
        name: "Go Start Community Transport",
        url: "https://www.traveline.info",
        phone: "",
        noc: "GOCT",
    },
    {
        id: 496,
        name: "Hadleigh Community Transport",
        url: "https://www.traveline.info",
        phone: "",
        noc: "HADC",
    },
    {
        id: 497,
        name: "High Suffolk Community Transport",
        url: "https://www.traveline.info",
        phone: "",
        noc: "HSCT",
    },
    {
        id: 498,
        name: "Halesworth Area Community Transport",
        url: "https://www.traveline.info",
        phone: "",
        noc: "HACT",
    },
    { id: 499, name: "The Voluntary Network", url: "https://www.traveline.info", phone: "", noc: "VOLN" },
    {
        id: 500,
        name: "Coastal Accessible Transport",
        url: "https://www.traveline.info",
        phone: "",
        noc: "CATS",
    },
    { id: 501, name: "Star Cabs", url: "https://www.traveline.info", phone: "", noc: "STCB" },
    { id: 502, name: "Borderbus", url: "https://www.traveline.info", phone: "", noc: "BDRB" },
    {
        id: 503,
        name: "Fareline Bus & Coach Services",
        url: "https://www.traveline.info",
        phone: "",
        noc: "FABC",
    },
    { id: 504, name: "Felix Taxis & Co.", url: "https://www.traveline.info", phone: "", noc: "FXTX" },
    { id: 506, name: "Mulleys Motorways", url: "https://www.traveline.info", phone: "", noc: "MULM" },
    { id: 507, name: "Harwich Harbour Ferry", url: "https://www.traveline.info", phone: "", noc: "HHFS" },
    {
        id: 508,
        name: "Felixstowe Ferry Boat Yard",
        url: "https://www.traveline.info",
        phone: "",
        noc: "FFBY",
    },
    { id: 510, name: "Beestons", url: "https://www.traveline.info", phone: "", noc: "BEES" },
    { id: 511, name: "First Aberdeen", url: "https://www.traveline.info", phone: "", noc: "FABD" },
    { id: 512, name: "Stagecoach Bluebird", url: "https://www.traveline.info", phone: "", noc: "SBLB" },
    { id: 516, name: "Deveron Coaches", url: "https://www.traveline.info", phone: "", noc: "DVRN" },
    { id: 519, name: "Fishers Tours", url: "https://www.traveline.info", phone: "", noc: "FSHT" },
    { id: 520, name: "Travel Wisharts", url: "https://www.traveline.info", phone: "", noc: "WSHT" },
    { id: 521, name: "J P Minibus", url: "https://www.traveline.info", phone: "", noc: "JPEM" },
    { id: 522, name: "County Travel", url: "https://www.traveline.info", phone: "", noc: "CNTT" },
    { id: 523, name: "Smith & Sons", url: "https://www.traveline.info", phone: "", noc: "SMTH" },
    { id: 524, name: "Xplore Dundee", url: "https://www.traveline.info", phone: "", noc: "TRDU" },
    { id: 525, name: "Moffat & Williamson", url: "https://www.traveline.info", phone: "", noc: "MOFF" },
    {
        id: 526,
        name: "Argyll & Bute Council Ferries",
        url: "https://www.traveline.info",
        phone: "",
        noc: "ABCF",
    },
    { id: 527, name: "Islay Sea Safari", url: "https://www.traveline.info", phone: "", noc: "NMKN" },
    { id: 528, name: "West Coast Motors", url: "https://www.traveline.info", phone: "", noc: "WCMO" },
    {
        id: 529,
        name: "Garelochhead Minibuses & Coaches",
        url: "https://www.traveline.info",
        phone: "",
        noc: "GLHD",
    },
    { id: 530, name: "Islay Coaches", url: "https://www.traveline.info", phone: "", noc: "ISLY" },
    { id: 532, name: "D A & A J MacLean", url: "https://www.traveline.info", phone: "", noc: "DAMC" },
    { id: 533, name: "John Kennedy", url: "https://www.traveline.info", phone: "", noc: "JOKN" },
    { id: 534, name: "Ulva Ferry", url: "https://www.traveline.info", phone: "", noc: "NULV" },
    { id: 536, name: "Scottish Borders Council", url: "https://www.traveline.info", phone: "", noc: "NSBC" },
    { id: 537, name: "Stagecoach West Scotland", url: "https://www.traveline.info", phone: "", noc: "STWS" },
    { id: 538, name: "DGC Buses", url: "https://www.traveline.info", phone: "", noc: "DGCB" },
    {
        id: 539,
        name: "Stagecoach Cumbria and North Lancashire",
        url: "https://www.traveline.info",
        phone: "",
        noc: "SCCU",
    },
    { id: 540, name: "W Brownrigg", url: "https://www.traveline.info", phone: "", noc: "BWGG" },
    { id: 541, name: "McCall's Coaches", url: "https://www.traveline.info", phone: "", noc: "MCCL" },
    { id: 543, name: "McCulloch's Coaches", url: "https://www.traveline.info", phone: "", noc: "MCHC" },
    {
        id: 544,
        name: "Wigtownshire Community Transport",
        url: "https://www.traveline.info",
        phone: "",
        noc: "SWCT",
    },
    { id: 545, name: "Scottish Citylink", url: "https://www.traveline.info", phone: "", noc: "SCLK" },
    { id: 546, name: "Edinburgh Coach Lines", url: "https://www.traveline.info", phone: "", noc: "ECLN" },
    { id: 548, name: "Prentice Coaches", url: "https://www.traveline.info", phone: "", noc: "DPCE" },
    { id: 549, name: "Eve Coaches", url: "https://www.traveline.info", phone: "", noc: "EVES" },
    { id: 550, name: "Stagecoach East Scotland", url: "https://www.traveline.info", phone: "", noc: "SCFI" },
    { id: 551, name: "A1 Coaches", url: "https://www.traveline.info", phone: "", noc: "A1CS" },
    { id: 552, name: "Bay Travel", url: "https://www.traveline.info", phone: "", noc: "SBAY" },
    { id: 553, name: "Festival Travel", url: "https://www.traveline.info", phone: "", noc: "NFST" },
    { id: 556, name: "Prentice Westwood", url: "https://www.traveline.info", phone: "", noc: "PWTD" },
    { id: 560, name: "Clydelink", url: "https://www.traveline.info", phone: "", noc: "NCLK" },
    { id: 561, name: "Caledonian MacBrayne", url: "https://www.traveline.info", phone: "", noc: "CALM" },
    {
        id: 562,
        name: "Skye Ferry Community Interest Company",
        url: "https://www.traveline.info",
        phone: "",
        noc: "NSFC",
    },
    {
        id: 563,
        name: "Scottish Citylink/Megabus jointly operated",
        url: "https://www.traveline.info",
        phone: "",
        noc: "SCMG",
    },
    { id: 564, name: "Megabus", url: "https://www.traveline.info", phone: "", noc: "MEGA" },
    { id: 565, name: "Northlink Ferries", url: "https://www.traveline.info", phone: "", noc: "NLKF" },
    {
        id: 567,
        name: "Scottish Citylink & Ulsterbus",
        url: "https://www.traveline.info",
        phone: "",
        noc: "SCUL",
    },
    { id: 568, name: "Pentland Ferries", url: "https://www.traveline.info", phone: "", noc: "PENT" },
    { id: 569, name: "Dodds of Troon", url: "https://www.traveline.info", phone: "", noc: "DODT" },
    { id: 570, name: "SPT Subway", url: "https://www.traveline.info", phone: "", noc: "SPTU" },
    { id: 571, name: "Hebridean MiniBus Service", url: "https://www.traveline.info", phone: "", noc: "HMSV" },
    { id: 572, name: "Lochs Motor Transport", url: "https://www.traveline.info", phone: "", noc: "LMTR" },
    { id: 573, name: "Murdo MacIver", url: "https://www.traveline.info", phone: "", noc: "MMIV" },
    { id: 574, name: "Hebridean Transport", url: "https://www.traveline.info", phone: "", noc: "HETR" },
    { id: 575, name: "Bus Na Comhairle", url: "https://www.traveline.info", phone: "", noc: "BNCM" },
    { id: 576, name: "Peter MacLennan", url: "https://www.traveline.info", phone: "", noc: "PMLN" },
    { id: 578, name: "South Harris Coaches", url: "https://www.traveline.info", phone: "", noc: "SHRS" },
    { id: 579, name: "D A Travel", url: "https://www.traveline.info", phone: "", noc: "DATR" },
    { id: 581, name: "Western Ferries", url: "https://www.traveline.info", phone: "", noc: "WFRL" },
    { id: 583, name: "Grenitote Travel", url: "https://www.traveline.info", phone: "", noc: "GRET" },
    { id: 584, name: "First Greater Glasgow", url: "https://www.traveline.info", phone: "", noc: "FGLA" },
    { id: 586, name: "Highland Council", url: "https://www.traveline.info", phone: "", noc: "HIGH" },
    { id: 587, name: "Shiel Buses", url: "https://www.traveline.info", phone: "", noc: "SHIL" },
    { id: 588, name: "George Rapson Travel", url: "https://www.traveline.info", phone: "", noc: "GRTL" },
    { id: 589, name: "D & E Coaches", url: "https://www.traveline.info", phone: "", noc: "DECO" },
    { id: 590, name: "A MacDonald", url: "https://www.traveline.info", phone: "", noc: "AMAC" },
    { id: 592, name: "Westerbus", url: "https://www.traveline.info", phone: "", noc: "WESB" },
    { id: 593, name: "D M K Motors", url: "https://www.traveline.info", phone: "", noc: "DMKM" },
    { id: 594, name: "The Durness Bus", url: "https://www.traveline.info", phone: "", noc: "NNIH" },
    { id: 595, name: "Taxi Service", url: "https://www.traveline.info", phone: "", noc: "TXIS" },
    { id: 596, name: "Lothian Buses", url: "https://www.traveline.info", phone: "", noc: "LOTH" },
    { id: 597, name: "Lothian Country Buses", url: "https://www.traveline.info", phone: "", noc: "NELB" },
    { id: 598, name: "East Coast Buses", url: "https://www.traveline.info", phone: "", noc: "ECBU" },
    { id: 599, name: "Edinburgh Trams", url: "https://www.traveline.info", phone: "", noc: "EDTR" },
    {
        id: 600,
        name: "Lothian Community Transport",
        url: "https://www.traveline.info",
        phone: "",
        noc: "LOCT",
    },
    { id: 601, name: "Moray Council", url: "https://www.traveline.info", phone: "", noc: "MCOL" },
    {
        id: 602,
        name: "Isle of Hoy Development Trust",
        url: "https://www.traveline.info",
        phone: "",
        noc: "SHDT",
    },
    { id: 604, name: "Orkney Ferries", url: "https://www.traveline.info", phone: "", noc: "OKFL" },
    { id: 605, name: "Dochertys Midland Coaches", url: "https://www.traveline.info", phone: "", noc: "DMCO" },
    { id: 606, name: "Burnbrae Garage", url: "https://www.traveline.info", phone: "", noc: "BBGG" },
    { id: 607, name: "Elizabeth Yule", url: "https://www.traveline.info", phone: "", noc: "YULE" },
    { id: 608, name: "Sweeneys Garage", url: "https://www.traveline.info", phone: "", noc: "SWGG" },
    { id: 610, name: "McColls Travel", url: "https://www.traveline.info", phone: "", noc: "MCLS" },
    { id: 611, name: "Colchri Coaches", url: "https://www.traveline.info", phone: "", noc: "COLC" },
    { id: 612, name: "McGill's Bus Service", url: "https://www.traveline.info", phone: "", noc: "MCGL" },
    { id: 615, name: "Stuart's Coaches", url: "https://www.traveline.info", phone: "", noc: "STUR" },
    { id: 616, name: "McNairn Coaches", url: "https://www.traveline.info", phone: "", noc: "MCNN" },
    { id: 617, name: "JMB Travel", url: "https://www.traveline.info", phone: "", noc: "NJMT" },
    { id: 618, name: "Shuttle Buses", url: "https://www.traveline.info", phone: "", noc: "SHUT" },
    { id: 620, name: "Canavan Travel", url: "https://www.traveline.info", phone: "", noc: "PCVN" },
    { id: 622, name: "Avondale Coaches", url: "https://www.traveline.info", phone: "", noc: "AVOD" },
    { id: 623, name: "ARG Travel", url: "https://www.traveline.info", phone: "", noc: "ARGT" },
    { id: 624, name: "Craigs of Cumbernauld", url: "https://www.traveline.info", phone: "", noc: "CRCD" },
    { id: 625, name: "Whitelaw Coaches", url: "https://www.traveline.info", phone: "", noc: "WHTL" },
    { id: 626, name: "Wilson's of Rhu", url: "https://www.traveline.info", phone: "", noc: "WRHU" },
    { id: 627, name: "Millport Motors", url: "https://www.traveline.info", phone: "", noc: "MPOM" },
    {
        id: 629,
        name: "Community Transport Glasgow",
        url: "https://www.traveline.info",
        phone: "",
        noc: "NCTG",
    },
    { id: 630, name: "United Coaches", url: "https://www.traveline.info", phone: "", noc: "UNTD" },
    {
        id: 632,
        name: "North Area Transport Association",
        url: "https://www.traveline.info",
        phone: "",
        noc: "NNAT",
    },
    {
        id: 634,
        name: "South Ayrshire Community Transport",
        url: "https://www.traveline.info",
        phone: "",
        noc: "SACT",
    },
    { id: 635, name: "Wilsons Buses", url: "https://www.traveline.info", phone: "", noc: "NCRC" },
    { id: 638, name: "J A & G D Nicolson", url: "https://www.traveline.info", phone: "", noc: "JADN" },
    { id: 640, name: "Wastbus", url: "https://www.traveline.info", phone: "", noc: "WSTS" },
    { id: 641, name: "Whites Coaches (Shetland)", url: "https://www.traveline.info", phone: "", noc: "GPWS" },
    { id: 644, name: "Martins Car Hire", url: "https://www.traveline.info", phone: "", noc: "MAHT" },
    { id: 645, name: "Johnson Transport", url: "https://www.traveline.info", phone: "", noc: "JFJT" },
    { id: 646, name: "R G Jamieson & Son", url: "https://www.traveline.info", phone: "", noc: "RGJS" },
    { id: 648, name: "R Robertson & Son", url: "https://www.traveline.info", phone: "", noc: "RRSN" },
    { id: 649, name: "Shetland Ferries", url: "https://www.traveline.info", phone: "", noc: "SHET" },
    { id: 650, name: "BK Marine", url: "https://www.traveline.info", phone: "", noc: "ATLF" },
    { id: 651, name: "Hunters Executive Coaches", url: "https://www.traveline.info", phone: "", noc: "HEXC" },
    { id: 654, name: "SD Travel", url: "https://www.traveline.info", phone: "", noc: "SDTR" },
    { id: 658, name: "York Pullman", url: "https://www.traveline.info", phone: "", noc: "KJTR" },
    { id: 659, name: "Goole Go Far", url: "https://www.traveline.info", phone: "", noc: "GOGF" },
    { id: 660, name: "Thornes Independent Ltd", url: "https://www.traveline.info", phone: "", noc: "THIL" },
    { id: 662, name: "Coastliner", url: "https://www.traveline.info", phone: "", noc: "YCST" },
    { id: 664, name: "The Harrogate Bus Company", url: "https://www.traveline.info", phone: "", noc: "HRGT" },
    { id: 665, name: "Arriva Yorkshire", url: "https://www.traveline.info", phone: "", noc: "WRAY" },
    {
        id: 666,
        name: "North Yorkshire County Council",
        url: "https://www.traveline.info",
        phone: "",
        noc: "NYCC",
    },
    { id: 667, name: "Dales and District", url: "https://www.traveline.info", phone: "", noc: "DDIS" },
    {
        id: 669,
        name: "Ryedale Community Transport",
        url: "https://www.traveline.info",
        phone: "",
        noc: "RYCA",
    },
    { id: 670, name: "SS Suncruisers", url: "https://www.traveline.info", phone: "", noc: "SSSN" },
    { id: 671, name: "Connexions Buses", url: "https://www.traveline.info", phone: "", noc: "HCTY" },
    { id: 672, name: "Reliance Motor Services", url: "https://www.traveline.info", phone: "", noc: "RELD" },
    { id: 673, name: "Upper Wharfedale Venturer", url: "https://www.traveline.info", phone: "", noc: "UWCB" },
    {
        id: 676,
        name: "Coastal and Country Coaches",
        url: "https://www.traveline.info",
        phone: "",
        noc: "CACC",
    },
    { id: 678, name: "R & S Watersons", url: "https://www.traveline.info", phone: "", noc: "RWSW" },
    { id: 679, name: "Globe Holidays", url: "https://www.traveline.info", phone: "", noc: "BBCG" },
    { id: 680, name: "Moxons Tours", url: "https://www.traveline.info", phone: "", noc: "MOXN" },
    { id: 681, name: "Peter Hodgson Travel", url: "https://www.traveline.info", phone: "", noc: "HDGT" },
    { id: 684, name: "Marsland Travel", url: "https://www.traveline.info", phone: "", noc: "MTLY" },
    {
        id: 685,
        name: "Sheffield Community Transport",
        url: "https://www.traveline.info",
        phone: "",
        noc: "SCTP",
    },
    { id: 686, name: "Camerons Travel", url: "https://www.traveline.info", phone: "", noc: "CAMT" },
    { id: 688, name: "First York", url: "https://www.traveline.info", phone: "", noc: "FYOR" },
    { id: 690, name: "St Ives Minibus Services", url: "https://www.traveline.info", phone: "", noc: "STIV" },
    { id: 691, name: "Fal River Links", url: "https://www.traveline.info", phone: "", noc: "KHFC" },
    { id: 692, name: "St Mawes Ferry", url: "https://www.traveline.info", phone: "", noc: "STMF" },
    { id: 693, name: "Roselyn Coaches", url: "https://www.traveline.info", phone: "", noc: "RSLN" },
    { id: 694, name: "Mevagissey Ferry", url: "https://www.traveline.info", phone: "", noc: "MSSW" },
    { id: 695, name: "Flushing Ferry", url: "https://www.traveline.info", phone: "", noc: "FLFY" },
    {
        id: 696,
        name: "Tamar Bridge & Torpoint Ferry Joint Committee",
        url: "https://www.traveline.info",
        phone: "",
        noc: "TBTJ",
    },
    { id: 697, name: "Travel Cornwall", url: "https://www.traveline.info", phone: "", noc: "SMMC" },
    { id: 699, name: "Plymouth Boat Trips", url: "https://www.traveline.info", phone: "", noc: "PBTR" },
    { id: 700, name: "Hopleys Coaches", url: "https://www.traveline.info", phone: "", noc: "HOPE" },
    { id: 701, name: "OTS", url: "https://www.traveline.info", phone: "", noc: "OTSS" },
    { id: 702, name: "Royal Buses", url: "https://www.traveline.info", phone: "", noc: "ESTW" },
    { id: 704, name: "Polruan Ferry Co Ltd", url: "https://www.traveline.info", phone: "", noc: "PFCL" },
    {
        id: 705,
        name: "Polruan Passenger Ferry, Bodinnick Vehicle Ferry",
        url: "https://www.traveline.info",
        phone: "",
        noc: "CTSL",
    },
    {
        id: 706,
        name: "Padstow Harbour Commissioners",
        url: "https://www.traveline.info",
        phone: "",
        noc: "PHCM",
    },
    {
        id: 707,
        name: "Isles of Scilly Steamship Co",
        url: "https://www.traveline.info",
        phone: "",
        noc: "ISSC",
    },
    { id: 708, name: "Dartline Coaches", url: "https://www.traveline.info", phone: "", noc: "DTCO" },
    { id: 709, name: "Oakleys Coaches", url: "https://www.traveline.info", phone: "", noc: "SWOC" },
    { id: 710, name: "Country Bus", url: "https://www.traveline.info", phone: "", noc: "CNTY" },
    { id: 711, name: "Tally Ho!", url: "https://www.traveline.info", phone: "", noc: "TLYH" },
    {
        id: 712,
        name: "Dawlish Community Transport",
        url: "https://www.traveline.info",
        phone: "",
        noc: "SWDC",
    },
    { id: 714, name: "Filers Travel", url: "https://www.traveline.info", phone: "", noc: "FTZL" },
    { id: 715, name: "Taw & Torridge", url: "https://www.traveline.info", phone: "", noc: "TAWT" },
    { id: 716, name: "Independent Coach Company", url: "https://www.traveline.info", phone: "", noc: "INDC" },
    {
        id: 717,
        name: "Newton Abbot Community Transport",
        url: "https://www.traveline.info",
        phone: "",
        noc: "NACT",
    },
    { id: 718, name: "Hatch Green Coaches", url: "https://www.traveline.info", phone: "", noc: "HGCO" },
    { id: 719, name: "Dartmouth Higher Ferry", url: "https://www.traveline.info", phone: "", noc: "DMHF" },
    { id: 720, name: "River Link", url: "https://www.traveline.info", phone: "", noc: "DPCR" },
    { id: 721, name: "Axe Valley Mini-Travel", url: "https://www.traveline.info", phone: "", noc: "AVMT" },
    { id: 723, name: "Redwoods Travel", url: "https://www.traveline.info", phone: "", noc: "NRTL" },
    {
        id: 724,
        name: "Dorset Community Transport",
        url: "https://www.traveline.info",
        phone: "",
        noc: "SDCT",
    },
    { id: 725, name: "Totness Community Bus", url: "https://www.traveline.info", phone: "", noc: "TOTN" },
    { id: 727, name: "Salcombe Ferry", url: "https://www.traveline.info", phone: "", noc: "SWSF" },
    { id: 728, name: "Plymouth Citybus", url: "https://www.traveline.info", phone: "", noc: "PLYC" },
    { id: 729, name: "Go Cornwall Bus", url: "https://www.traveline.info", phone: "", noc: "TFCN" },
    { id: 730, name: "Stagecoach South West", url: "https://www.traveline.info", phone: "", noc: "SDVN" },
    { id: 731, name: "First Kernow", url: "https://www.traveline.info", phone: "", noc: "FCWL" },
    { id: 732, name: "Mountbatten Water Taxis", url: "https://www.traveline.info", phone: "", noc: "MBWT" },
    { id: 733, name: "Torbay Buses", url: "https://www.traveline.info", phone: "", noc: "DJWA" },
    { id: 735, name: "Stagecoach West", url: "https://www.traveline.info", phone: "", noc: "SCGL" },
    {
        id: 736,
        name: "First Bristol, Bath & the West",
        url: "https://www.traveline.info",
        phone: "",
        noc: "FBRI",
    },
    { id: 742, name: "CT Coaches", url: "https://www.traveline.info", phone: "", noc: "CTCO" },
    { id: 743, name: "Faresaver", url: "https://www.traveline.info", phone: "", noc: "FSRV" },
    { id: 744, name: "ABUS", url: "https://www.traveline.info", phone: "", noc: "ABUS" },
    { id: 746, name: "FromeBus", url: "https://www.traveline.info", phone: "", noc: "FRMN" },
    { id: 748, name: "Bath Bus Company", url: "https://www.traveline.info", phone: "", noc: "BBCL" },
    { id: 749, name: "First Buses of Somerset", url: "https://www.traveline.info", phone: "", noc: "FBOS" },
    { id: 750, name: "Atwest", url: "https://www.traveline.info", phone: "", noc: "ATWE" },
    { id: 751, name: "W Ridler & Sons", url: "https://www.traveline.info", phone: "", noc: "RIDL" },
    { id: 752, name: "South West Coaches", url: "https://www.traveline.info", phone: "", noc: "SWCO" },
    { id: 753, name: "Somerset Council", url: "https://www.traveline.info", phone: "", noc: "SMST" },
    { id: 754, name: "Libra Travel", url: "https://www.traveline.info", phone: "", noc: "LTRV" },
    { id: 755, name: "Berry's Coaches", url: "https://www.traveline.info", phone: "", noc: "BYCO" },
    { id: 756, name: "Isle Valley Transport", url: "https://www.traveline.info", phone: "", noc: "IVTR" },
    {
        id: 757,
        name: "South Somerset Community Transport",
        url: "https://www.traveline.info",
        phone: "",
        noc: "SSCT",
    },
    { id: 758, name: "Bakers Dolphin", url: "https://www.traveline.info", phone: "", noc: "BDOL" },
    {
        id: 759,
        name: "Mendip Community Transport",
        url: "https://www.traveline.info",
        phone: "",
        noc: "MNCT",
    },
    { id: 761, name: "Isle of Wedmore RT Assoc.", url: "https://www.traveline.info", phone: "", noc: "IWRA" },
    {
        id: 762,
        name: "First Wessex, Dorset & South Somerset",
        url: "https://www.traveline.info",
        phone: "",
        noc: "FDOR",
    },
    { id: 763, name: "Damory Coaches", url: "https://www.traveline.info", phone: "", noc: "DAMY" },
    { id: 764, name: "morebus", url: "https://www.traveline.info", phone: "", noc: "WDBC" },
    { id: 767, name: "Discover Dorset Tours", url: "https://www.traveline.info", phone: "", noc: "DDLT" },
    { id: 768, name: "Sandbanks Ferry", url: "https://www.traveline.info", phone: "", noc: "SBFY" },
    {
        id: 770,
        name: "Hampshire Community Transport",
        url: "https://www.traveline.info",
        phone: "",
        noc: "HCCT",
    },
    { id: 771, name: "Bluestar", url: "https://www.traveline.info", phone: "", noc: "BLUS" },
    {
        id: 772,
        name: "First Portsmouth, Fareham & Gosport",
        url: "https://www.traveline.info",
        phone: "",
        noc: "FHAM",
    },
    { id: 773, name: "Southern Vectis", url: "https://www.traveline.info", phone: "", noc: "SVCT" },
    { id: 774, name: "Cresta Coaches", url: "https://www.traveline.info", phone: "", noc: "CRES" },
    { id: 776, name: "AMK", url: "https://www.traveline.info", phone: "", noc: "AMKC" },
    { id: 777, name: "Community First Wessex", url: "https://www.traveline.info", phone: "", noc: "CFWX" },
    {
        id: 778,
        name: "Basingstoke Community Transport",
        url: "https://www.traveline.info",
        phone: "",
        noc: "SWBC",
    },
    { id: 780, name: "Salisbury Reds", url: "https://www.traveline.info", phone: "", noc: "SWWD" },
    { id: 781, name: "FYTbus", url: "https://www.traveline.info", phone: "", noc: "FYTB" },
    { id: 782, name: "Xelabus", url: "https://www.traveline.info", phone: "", noc: "XLBL" },
    { id: 784, name: "Uni-Link", url: "https://www.traveline.info", phone: "", noc: "UNIL" },
    { id: 785, name: "Cowes Ferry", url: "https://www.traveline.info", phone: "", noc: "IOWC" },
    { id: 786, name: "Gosport-Portsmouth Ferry", url: "https://www.traveline.info", phone: "", noc: "GOSF" },
    { id: 787, name: "Hayling Ferry Limited", url: "https://www.traveline.info", phone: "", noc: "HAYL" },
    { id: 788, name: "White Horse Ferries", url: "https://www.traveline.info", phone: "", noc: "WHFR" },
    { id: 789, name: "Hovertravel", url: "https://www.traveline.info", phone: "", noc: "HOVT" },
    { id: 790, name: "Red Funnel", url: "https://www.traveline.info", phone: "", noc: "RF" },
    { id: 791, name: "WightLink", url: "https://www.traveline.info", phone: "", noc: "WLKF" },
    { id: 792, name: "Robert Eugene Dix", url: "https://www.traveline.info", phone: "", noc: "RESW" },
    {
        id: 793,
        name: "Cheltenham Community Transport",
        url: "https://www.traveline.info",
        phone: "",
        noc: "SWCC",
    },
    { id: 794, name: "Cotswold Green", url: "https://www.traveline.info", phone: "", noc: "COTS" },
    { id: 796, name: "Ebley Coaches", url: "https://www.traveline.info", phone: "", noc: "EBLY" },
    {
        id: 799,
        name: "Forest Community Transport",
        url: "https://www.traveline.info",
        phone: "",
        noc: "SWFC",
    },
    { id: 800, name: "K B Coaches", url: "https://www.traveline.info", phone: "", noc: "KBCO" },
    { id: 801, name: "Swanbrook Coaches", url: "https://www.traveline.info", phone: "", noc: "SWAN" },
    { id: 802, name: "Nick Maddy Coaches", url: "https://www.traveline.info", phone: "", noc: "NMCO" },
    { id: 803, name: "N N Cresswell", url: "https://www.traveline.info", phone: "", noc: "CRSS" },
    { id: 805, name: "F R Willetts", url: "https://www.traveline.info", phone: "", noc: "GWIL" },
    { id: 807, name: "Chepstow Classic Buses", url: "https://www.traveline.info", phone: "", noc: "CHCB" },
    { id: 808, name: "Grindles Coaches", url: "https://www.traveline.info", phone: "", noc: "GRIN" },
    { id: 809, name: "Marchants Coaches", url: "https://www.traveline.info", phone: "", noc: "MARC" },
    { id: 810, name: "Taylors Travel", url: "https://www.traveline.info", phone: "", noc: "TYSW" },
    { id: 811, name: "Swindon's Bus Company", url: "https://www.traveline.info", phone: "", noc: "TDTR" },
    { id: 812, name: "Coachstyle", url: "https://www.traveline.info", phone: "", noc: "COAC" },
    { id: 814, name: "Beeline Coaches", url: "https://www.traveline.info", phone: "", noc: "BZCO" },
    { id: 815, name: "4K Travel", url: "https://www.traveline.info", phone: "", noc: "NAKL" },
    { id: 816, name: "Three Villages MiniBus", url: "https://www.traveline.info", phone: "", noc: "EECC" },
    {
        id: 817,
        name: "Community Transport South Wiltshire",
        url: "https://www.traveline.info",
        phone: "",
        noc: "CTSW",
    },
    { id: 818, name: "Ramsbury Community Bus", url: "https://www.traveline.info", phone: "", noc: "RMCB" },
    { id: 819, name: "The Seend Shuttle", url: "https://www.traveline.info", phone: "", noc: "SNDS" },
    { id: 820, name: "Connect2Wiltshire", url: "https://www.traveline.info", phone: "", noc: "C2WI" },
    { id: 822, name: "Eurocoaches", url: "https://www.traveline.info", phone: "", noc: "EUTX" },
    { id: 825, name: "Taf Valley Coaches", url: "https://www.traveline.info", phone: "", noc: "TAFV" },
    { id: 827, name: "London Underground (TfL)", url: "https://www.traveline.info", phone: "", noc: "LULD" },
    {
        id: 828,
        name: "London Docklands Light Railway - TfL",
        url: "https://www.traveline.info",
        phone: "",
        noc: "LDLR",
    },
    { id: 831, name: "Woolwich Free Ferry", url: "https://www.traveline.info", phone: "", noc: "NWFF" },
    { id: 833, name: "London Tramlink", url: "https://www.traveline.info", phone: "", noc: "TRAM" },
    { id: 839, name: "Arriva London", url: "https://www.traveline.info", phone: "", noc: "AVLO" },
    { id: 841, name: "Townlynx", url: "https://www.traveline.info", phone: "", noc: "TNLX" },
    { id: 842, name: "Yeomans Travel", url: "https://www.traveline.info", phone: "", noc: "YEOC" },
    { id: 843, name: "Lugg Valley Travel", url: "https://www.traveline.info", phone: "", noc: "LVTR" },
    { id: 844, name: "DRM Bus", url: "https://www.traveline.info", phone: "", noc: "DRMC" },
    { id: 845, name: "Newent Community Link", url: "https://www.traveline.info", phone: "", noc: "WNCL" },
    { id: 846, name: "Bennetts Travel", url: "https://www.traveline.info", phone: "", noc: "BENC" },
    { id: 847, name: "Stanton's of Stoke", url: "https://www.traveline.info", phone: "", noc: "SOST" },
    { id: 848, name: "Caradoc Coaches", url: "https://www.traveline.info", phone: "", noc: "CARA" },
    { id: 849, name: "Lakeside Coaches", url: "https://www.traveline.info", phone: "", noc: "LAKC" },
    { id: 850, name: "Minsterley", url: "https://www.traveline.info", phone: "", noc: "MINS" },
    { id: 851, name: "Yarranton Brothers", url: "https://www.traveline.info", phone: "", noc: "YTNB" },
    { id: 852, name: "R & B Travel", url: "https://www.traveline.info", phone: "", noc: "RBTR" },
    { id: 853, name: "First Potteries", url: "https://www.traveline.info", phone: "", noc: "FPOT" },
    { id: 854, name: "Scraggs", url: "https://www.traveline.info", phone: "", noc: "SCRT" },
    { id: 856, name: "Hedgehog Community Bus", url: "https://www.traveline.info", phone: "", noc: "HCBU" },
    { id: 857, name: "Lilbourne Community Bus", url: "https://www.traveline.info", phone: "", noc: "LCMB" },
    { id: 858, name: "Wyre Forest Dial a Ride", url: "https://www.traveline.info", phone: "", noc: "WWFD" },
    { id: 860, name: "Astons Coaches", url: "https://www.traveline.info", phone: "", noc: "ASTC" },
    { id: 861, name: "LMS Travel", url: "https://www.traveline.info", phone: "", noc: "LMST" },
    { id: 862, name: "Hollands Coaches", url: "https://www.traveline.info", phone: "", noc: "HOCO" },
    { id: 865, name: "Finesse Travel", url: "https://www.traveline.info", phone: "", noc: "FINT" },
    { id: 866, name: "Henshaw's Coaches", url: "https://www.traveline.info", phone: "", noc: "HENS" },
    { id: 867, name: "Valentines Travel", url: "https://www.traveline.info", phone: "", noc: "VALT" },
    { id: 868, name: "Village & Valleys Travel", url: "https://www.traveline.info", phone: "", noc: "VIVA" },
    { id: 869, name: "Wrexham Taxis", url: "https://www.traveline.info", phone: "", noc: "WTAX" },
    { id: 926, name: "A Lyles and Son", url: "https://www.traveline.info", phone: "", noc: "LNGS" },
    { id: 927, name: "Stotts Coaches", url: "https://www.traveline.info", phone: "", noc: "ESTS" },
    { id: 928, name: "Globe Coaches", url: "https://www.traveline.info", phone: "", noc: "GLCS" },
    { id: 929, name: "Station Coaches", url: "https://www.traveline.info", phone: "", noc: "YSTN" },
    { id: 930, name: "TLC Travel Ltd", url: "https://www.traveline.info", phone: "", noc: "TLCT" },
    { id: 931, name: "First Leeds", url: "https://www.traveline.info", phone: "", noc: "FLDS" },
    { id: 932, name: "Squarepeg", url: "https://www.traveline.info", phone: "", noc: "YSQU" },
    { id: 933, name: "First Bradford", url: "https://www.traveline.info", phone: "", noc: "FBRA" },
    { id: 934, name: "Ross Travel", url: "https://www.traveline.info", phone: "", noc: "ROSS" },
    { id: 935, name: "Stevenson's Travel", url: "https://www.traveline.info", phone: "", noc: "STTR" },
    { id: 936, name: "Jacksons of Silsden Ltd", url: "https://www.traveline.info", phone: "", noc: "JASI" },
    { id: 937, name: "Wharfeconnections", url: "https://www.traveline.info", phone: "", noc: "HGCT" },
    { id: 938, name: "Tetley's", url: "https://www.traveline.info", phone: "", noc: "TTLY" },
    { id: 963, name: "Fords Coaches", url: "https://www.traveline.info", phone: "", noc: "FRDS" },
    { id: 965, name: "Ember", url: "https://www.traveline.info", phone: "", noc: "EMBR" },
    {
        id: 966,
        name: "Tavistock Community Transport",
        url: "https://www.traveline.info",
        phone: "",
        noc: "TVCT",
    },
    { id: 991, name: "Watermill Coaches", url: "https://www.traveline.info", phone: "", noc: "WTRM" },
    { id: 1024, name: "Stagecoach Highlands", url: "https://www.traveline.info", phone: "", noc: "SCHI" },
    { id: 1060, name: "Flagfinders", url: "https://www.traveline.info", phone: "", noc: "SEFF" },
    { id: 1092, name: "Mersey Ferries", url: "https://www.traveline.info", phone: "", noc: "FRRY" },
    {
        id: 1095,
        name: "Meon Valley Community Bus",
        url: "https://www.traveline.info",
        phone: "",
        noc: "MVCB",
    },
    {
        id: 1123,
        name: "South Yorkshire Future Tram",
        url: "https://www.traveline.info",
        phone: "",
        noc: "SYFT",
    },
    { id: 1225, name: "D & P Boat Hire", url: "https://www.traveline.info", phone: "", noc: "DPBO" },
    {
        id: 1291,
        name: "Stansted Airport Hotel Shuttle",
        url: "https://www.traveline.info",
        phone: "",
        noc: "BAAS",
    },
    {
        id: 1292,
        name: "Brentwood Community Transport",
        url: "https://www.traveline.info",
        phone: "",
        noc: "BRCT",
    },
    { id: 1293, name: "Coggeshall Community Bus", url: "https://www.traveline.info", phone: "", noc: "CGCB" },
    { id: 1295, name: "Gem Travel", url: "https://www.traveline.info", phone: "", noc: "GATS" },
    {
        id: 1296,
        name: "Amberley & Slindon Community Bus",
        url: "https://www.traveline.info",
        phone: "",
        noc: "ASLN",
    },
    {
        id: 1297,
        name: "Battle Area Community Transport",
        url: "https://www.traveline.info",
        phone: "",
        noc: "BACT",
    },
    { id: 1299, name: "Beaminster Town Council", url: "https://www.traveline.info", phone: "", noc: "BTCO" },
    { id: 1321, name: "Iain McGregor", url: "https://www.traveline.info", phone: "", noc: "IMAC" },
    {
        id: 1387,
        name: "Braintree Community Transport",
        url: "https://www.traveline.info",
        phone: "",
        noc: "BCMT",
    },
    {
        id: 1388,
        name: "Basildon District Volunteer Carers",
        url: "https://www.traveline.info",
        phone: "",
        noc: "BDVC",
    },
    { id: 1389, name: "Belle Vue Coaches", url: "https://www.traveline.info", phone: "", noc: "BEVC" },
    { id: 1399, name: "TK Travel", url: "https://www.traveline.info", phone: "", noc: "TKTR" },
    { id: 1454, name: "Coventry Minibuses", url: "https://www.traveline.info", phone: "", noc: "COMI" },
    { id: 1486, name: "Clearway of Catshill", url: "https://www.traveline.info", phone: "", noc: "CRWY" },
    { id: 1520, name: "Yeos Contracts", url: "https://www.traveline.info", phone: "", noc: "YEOS" },
    { id: 1554, name: "Stringers", url: "https://www.traveline.info", phone: "", noc: "SPMW" },
    { id: 1555, name: "Steve Keats of Sheffield", url: "https://www.traveline.info", phone: "", noc: "STEK" },
    { id: 1585, name: "Bullocks Coaches", url: "https://www.traveline.info", phone: "", noc: "BULL" },
    { id: 1619, name: "Lawson's of Corby", url: "https://www.traveline.info", phone: "", noc: "LAWS" },
    { id: 1620, name: "Reading RailAir", url: "https://www.traveline.info", phone: "", noc: "RRAR" },
    { id: 1783, name: "Andersons of Langholm", url: "https://www.traveline.info", phone: "", noc: "ANDL" },
    { id: 1849, name: "Kilvingtons of Leeds", url: "https://www.traveline.info", phone: "", noc: "KILV" },
    { id: 1916, name: "BM Coaches", url: "https://www.traveline.info", phone: "", noc: "BMCS" },
    { id: 2014, name: "Uno", url: "https://www.traveline.info", phone: "", noc: "UNIB" },
    { id: 2047, name: "igo", url: "https://www.traveline.info", phone: "", noc: "IGOB" },
    {
        id: 2146,
        name: "Waverley Hoppa Community Transport",
        url: "https://www.traveline.info",
        phone: "",
        noc: "WHOP",
    },
    { id: 2183, name: "MD Coaches", url: "https://www.traveline.info", phone: "", noc: "LIHO" },
    { id: 2212, name: "Bennetts", url: "https://www.traveline.info", phone: "", noc: "BNNT" },
    { id: 2245, name: "Borders Buses", url: "https://www.traveline.info", phone: "", noc: "PERY" },
    { id: 2278, name: "TransportConnect", url: "https://www.traveline.info", phone: "", noc: "TCNT" },
    {
        id: 2347,
        name: "Stagecoach Cumbria and North Lancashire",
        url: "https://www.traveline.info",
        phone: "",
        noc: "SCNW",
    },
    { id: 2350, name: "First Halifax", url: "https://www.traveline.info", phone: "", noc: "FHAL" },
    { id: 2476, name: "Chaserider", url: "https://www.traveline.info", phone: "", noc: "CRDR" },
    { id: 2477, name: "Arriva Derby", url: "https://www.traveline.info", phone: "", noc: "ADER" },
    {
        id: 2509,
        name: "Shires Passenger Transport",
        url: "https://www.traveline.info",
        phone: "",
        noc: "SHPT",
    },
    { id: 2707, name: "J Robinson Taxis", url: "https://www.traveline.info", phone: "", noc: "JROB" },
    { id: 2872, name: "Berwick Buses", url: "https://www.traveline.info", phone: "", noc: "KLEG" },
    { id: 2905, name: "HcL", url: "https://www.traveline.info", phone: "", noc: "HCLT" },
    { id: 2939, name: "Acme Transport Services", url: "https://www.traveline.info", phone: "", noc: "ACME" },
    { id: 2944, name: "Ambassador Travel", url: "https://www.traveline.info", phone: "", noc: "AMBS" },
    { id: 2945, name: "Keane Travel", url: "https://www.traveline.info", phone: "", noc: "KETR" },
    { id: 2949, name: "Britannia Coaches", url: "https://www.traveline.info", phone: "", noc: "CARL" },
    { id: 2950, name: "Phoenix Taxis", url: "https://www.traveline.info", phone: "", noc: "PHXT" },
    { id: 3202, name: "Harpenden Connect", url: "https://www.traveline.info", phone: "", noc: "HPDN" },
    { id: 3268, name: "Bibby's of Ingleton Ltd", url: "https://www.traveline.info", phone: "", noc: "BOIN" },
    { id: 3334, name: "The London Bus Company", url: "https://www.traveline.info", phone: "", noc: "LVBH" },
    { id: 3335, name: "Andrew's", url: "https://www.traveline.info", phone: "", noc: "ANRW" },
    {
        id: 3369,
        name: "Hartley Wintney Community Bus",
        url: "https://www.traveline.info",
        phone: "",
        noc: "HWCB",
    },
    { id: 3433, name: "J & D S Halcrow", url: "https://www.traveline.info", phone: "", noc: "HALC" },
    { id: 3466, name: "Jones Login", url: "https://www.traveline.info", phone: "", noc: "JLGN" },
    { id: 3631, name: "A B Coaches", url: "https://www.traveline.info", phone: "", noc: "NABC" },
    { id: 3665, name: "AK Transport", url: "https://www.traveline.info", phone: "", noc: "AKTS" },
    { id: 3666, name: "Wilma Ann Nicolson", url: "https://www.traveline.info", phone: "", noc: "WANN" },
    { id: 4027, name: "trentbarton", url: "https://www.traveline.info", phone: "", noc: "BRTB" },
    { id: 4061, name: "Rooster Bus", url: "https://www.traveline.info", phone: "", noc: "ROOS" },
    { id: 4225, name: "Jonathan Boyd", url: "https://www.traveline.info", phone: "", noc: "BOYD" },
    { id: 4258, name: "Community Action Dacorum", url: "https://www.traveline.info", phone: "", noc: "DACV" },
    {
        id: 4259,
        name: "Keith and Dufftown Railway",
        url: "https://www.traveline.info",
        phone: "",
        noc: "KDRW",
    },
    { id: 4260, name: "Cruise Loch Lomond", url: "https://www.traveline.info", phone: "", noc: "NCLL" },
    { id: 4261, name: "Ardlui Hotel", url: "https://www.traveline.info", phone: "", noc: "ARDS" },
    { id: 4262, name: "Strathspey Steam Railway", url: "https://www.traveline.info", phone: "", noc: "SSRW" },
    { id: 4263, name: "Arisaig Marine", url: "https://www.traveline.info", phone: "", noc: "ARIS" },
    { id: 4357, name: "HART", url: "https://www.traveline.info", phone: "", noc: "YHAR" },
    { id: 4423, name: "Hobson Travel", url: "https://www.traveline.info", phone: "", noc: "HOBS" },
    {
        id: 4424,
        name: "East Hull Community Transport",
        url: "https://www.traveline.info",
        phone: "",
        noc: "EHCT",
    },
    { id: 4458, name: "Compo", url: "https://www.traveline.info", phone: "", noc: "COMP" },
    { id: 4522, name: "Team Pennine", url: "https://www.traveline.info", phone: "", noc: "TPEN" },
    { id: 4555, name: "Belle Coaches", url: "https://www.traveline.info", phone: "", noc: "BLCO" },
    { id: 4621, name: "RS Taxis and Minicoaches", url: "https://www.traveline.info", phone: "", noc: "RSTA" },
    { id: 4623, name: "PVT Transfer", url: "https://www.traveline.info", phone: "", noc: "PVTT" },
    { id: 4853, name: "Our Bus", url: "https://www.traveline.info", phone: "", noc: "OBUS" },
    { id: 4951, name: "Bluebell Railway", url: "https://www.traveline.info", phone: "", noc: "BBRW" },
    {
        id: 4952,
        name: "Kent & East Sussex Railway",
        url: "https://www.traveline.info",
        phone: "",
        noc: "KESR",
    },
    {
        id: 5017,
        name: "Gorran & District Community Bus",
        url: "https://www.traveline.info",
        phone: "",
        noc: "GDCS",
    },
    { id: 5050, name: "National Express", url: "https://www.traveline.info", phone: "", noc: "NATX" },
    { id: 5051, name: "Flixbus", url: "https://www.traveline.info", phone: "", noc: "FLIX" },
    { id: 5116, name: "Mil-Ken Travel", url: "https://www.traveline.info", phone: "", noc: "MKEN" },
    { id: 5248, name: "Herberts Travel", url: "https://www.traveline.info", phone: "", noc: "HRBT" },
    { id: 5249, name: "Swanage Railway Company", url: "https://www.traveline.info", phone: "", noc: "SWNR" },
    { id: 5250, name: "John Dix Travel", url: "https://www.traveline.info", phone: "", noc: "JDXT" },
    { id: 5281, name: "Logan Rock Cars", url: "https://www.traveline.info", phone: "", noc: "LRCA" },
    { id: 5413, name: "Direct Taxis", url: "https://www.traveline.info", phone: "", noc: "ALLA" },
    { id: 5446, name: "Airport Bus Express", url: "https://www.traveline.info", phone: "", noc: "APBX" },
    { id: 5546, name: "Cawthorne's Travel", url: "https://www.traveline.info", phone: "", noc: "CAWT" },
    { id: 5547, name: "Heatons Coaches", url: "https://www.traveline.info", phone: "", noc: "WCTY" },
    { id: 5611, name: "Stanley Travel", url: "https://www.traveline.info", phone: "", noc: "STNT" },
    { id: 5875, name: "Fourways Coaches", url: "https://www.traveline.info", phone: "", noc: "FWAY" },
    { id: 6007, name: "Keepings Coaches", url: "https://www.traveline.info", phone: "", noc: "KEEP" },
    {
        id: 6008,
        name: "Exe Valley and Community Bus",
        url: "https://www.traveline.info",
        phone: "",
        noc: "EVCB",
    },
    { id: 6041, name: "Lucketts Travel", url: "https://www.traveline.info", phone: "", noc: "LUCK" },
    {
        id: 6205,
        name: "Lochaber Action on Disability",
        url: "https://www.traveline.info",
        phone: "",
        noc: "NLAD",
    },
    { id: 6207, name: "Lochcarron Garage", url: "https://www.traveline.info", phone: "", noc: "LCGG" },
    { id: 6271, name: "Harris Travel", url: "https://www.traveline.info", phone: "", noc: "HART" },
    { id: 6337, name: "Dan's Coach Travel", url: "https://www.traveline.info", phone: "", noc: "DNCT" },
    { id: 6502, name: "First & Last Mile", url: "https://www.traveline.info", phone: "", noc: "FALM" },
    { id: 6535, name: "Cavern City Tours", url: "https://www.traveline.info", phone: "", noc: "CAVE" },
    { id: 6700, name: "Black Cat Travel", url: "https://www.traveline.info", phone: "", noc: "BLCT" },
    { id: 6733, name: "Short's Travel", url: "https://www.traveline.info", phone: "", noc: "SHOT" },
    { id: 6800, name: "WMV Motor Hirer", url: "https://www.traveline.info", phone: "", noc: "WMVM" },
    { id: 6801, name: "Flyer", url: "https://www.traveline.info", phone: "", noc: "FLYE" },
    { id: 6832, name: "Greenslades Tours", url: "https://www.traveline.info", phone: "", noc: "GNSL" },
    { id: 7063, name: "Chatterbus", url: "https://www.traveline.info", phone: "", noc: "CHAT" },
    {
        id: 7195,
        name: "Bristol Ferry Boat Company",
        url: "https://www.traveline.info",
        phone: "",
        noc: "BFBC",
    },
    { id: 7228, name: "M & R Travel", url: "https://www.traveline.info", phone: "", noc: "MAND" },
    { id: 7261, name: "Marshalls Coaches", url: "https://www.traveline.info", phone: "", noc: "MSHC" },
    { id: 7360, name: "Minibus Plus.com", url: "https://www.traveline.info", phone: "", noc: "MBUP" },
    { id: 7393, name: "CommMiniBus", url: "https://www.traveline.info", phone: "", noc: "COMM" },
    { id: 7426, name: "Historic Scotland", url: "https://www.traveline.info", phone: "", noc: "HIST" },
    {
        id: 7427,
        name: "Steam Ship Sir Walter Scott",
        url: "https://www.traveline.info",
        phone: "",
        noc: "SWSS",
    },
    {
        id: 7428,
        name: "Leadhills and Wanlockhead Railway",
        url: "https://www.traveline.info",
        phone: "",
        noc: "LWRS",
    },
    { id: 7492, name: "Highland Ferries", url: "https://www.traveline.info", phone: "", noc: "HFRS" },
    {
        id: 7591,
        name: "Bo'ness and Kinneil Railway",
        url: "https://www.traveline.info",
        phone: "",
        noc: "BNKR",
    },
    { id: 7690, name: "Link Network", url: "https://www.traveline.info", phone: "", noc: "MDBC" },
    { id: 8055, name: "Hunter Cabs & Mini Buses", url: "https://www.traveline.info", phone: "", noc: "HCAB" },
    { id: 8218, name: "Green Mountain Travel", url: "https://www.traveline.info", phone: "", noc: "GMTL" },
    { id: 8482, name: "Ashcrofts Mini Travel", url: "https://www.traveline.info", phone: "", noc: "ASMT" },
    { id: 8515, name: "Scoraig Ferry", url: "https://www.traveline.info", phone: "", noc: "NSCR" },
    { id: 8516, name: "Tranport for Tongue", url: "https://www.traveline.info", phone: "", noc: "STFT" },
    { id: 8581, name: "Wilfreda Beehive", url: "https://www.traveline.info", phone: "", noc: "WBHV" },
    { id: 8680, name: "Transpora Bus", url: "https://www.traveline.info", phone: "", noc: "ALTO" },
    { id: 8713, name: "Galleon Travel", url: "https://www.traveline.info", phone: "", noc: "GLLN" },
    { id: 8714, name: "Catterall's", url: "https://www.traveline.info", phone: "", noc: "CTLL" },
    {
        id: 8746,
        name: "Derbyshire Community Transport",
        url: "https://www.traveline.info",
        phone: "",
        noc: "CT4T",
    },
    { id: 8747, name: "Eastern Scottish", url: "https://www.traveline.info", phone: "", noc: "MESC" },
    { id: 8781, name: "Midland Bluebird", url: "https://www.traveline.info", phone: "", noc: "MBLB" },
    { id: 8878, name: "Astra Coach Travel", url: "https://www.traveline.info", phone: "", noc: "ACTL" },
    { id: 8911, name: "David Goodfellow Travel", url: "https://www.traveline.info", phone: "", noc: "DGTR" },
    { id: 8944, name: "A&A Coach Travel", url: "https://www.traveline.info", phone: "", noc: "AACT" },
    { id: 8945, name: "Yorkshire Travel Group", url: "https://www.traveline.info", phone: "", noc: "YYTG" },
    {
        id: 8978,
        name: "Climate Action Strathaven",
        url: "https://www.traveline.info",
        phone: "",
        noc: "CLAS",
    },
    { id: 9175, name: "Vickery's Coaches", url: "https://www.traveline.info", phone: "", noc: "MART" },
    { id: 9275, name: "Sweyne Coaches", url: "https://www.traveline.info", phone: "", noc: "SWEY" },
    { id: 9406, name: "The Big Lemon", url: "https://www.traveline.info", phone: "", noc: "LEMB" },
    { id: 9538, name: "MacLeod's Coaches", url: "https://www.traveline.info", phone: "", noc: "WAEN" },
    { id: 9539, name: "Aarons of Wick", url: "https://www.traveline.info", phone: "", noc: "ARSH" },
    { id: 9540, name: "Dunnett's Transport", url: "https://www.traveline.info", phone: "", noc: "DUTR" },
    { id: 9572, name: "Mackie's Coaches", url: "https://www.traveline.info", phone: "", noc: "MKCO" },
    {
        id: 9638,
        name: "Taunton School Enterprises",
        url: "https://www.traveline.info",
        phone: "",
        noc: "TSCE",
    },
    { id: 9639, name: "CitySightseeing Oxford", url: "https://www.traveline.info", phone: "", noc: "CSSO" },
    { id: 9703, name: "Wright Way To Travel", url: "https://www.traveline.info", phone: "", noc: "ANWR" },
    {
        id: 9736,
        name: "Hadlow Rural Community School",
        url: "https://www.traveline.info",
        phone: "",
        noc: "HRCS",
    },
    { id: 9902, name: "Saltash Red Bus", url: "https://www.traveline.info", phone: "", noc: "SRBU" },
    { id: 10066, name: "K and K Transport", url: "https://www.traveline.info", phone: "", noc: "KKTR" },
    { id: 10232, name: "Solus Coaches", url: "https://www.traveline.info", phone: "", noc: "SOLU" },
    { id: 10363, name: "Galson Motors", url: "https://www.traveline.info", phone: "", noc: "GALM" },
    {
        id: 10396,
        name: "North Lincolnshire Council",
        url: "https://www.traveline.info",
        phone: "",
        noc: "NLCL",
    },
    {
        id: 10594,
        name: "Glenfarg Community Transport Group",
        url: "https://www.traveline.info",
        phone: "",
        noc: "GCTG",
    },
    {
        id: 10660,
        name: "Broughton & Mottisfont Community Bus",
        url: "https://www.traveline.info",
        phone: "",
        noc: "BMVB",
    },
    {
        id: 10792,
        name: "LA Travel (South Staffs Coach Hire)",
        url: "https://www.traveline.info",
        phone: "",
        noc: "LATR",
    },
    { id: 10825, name: "WM Travel", url: "https://www.traveline.info", phone: "", noc: "WIMC" },
    {
        id: 10858,
        name: "Bungay & Beccles Community Transport",
        url: "https://www.traveline.info",
        phone: "",
        noc: "BBCT",
    },
    { id: 10861, name: "Lichfield City Coaches", url: "https://www.traveline.info", phone: "", noc: "LCCO" },
    { id: 10924, name: "Bee Network", url: "https://www.traveline.info", phone: "", noc: "BNSM" },
    { id: 10990, name: "Forge Travel", url: "https://www.traveline.info", phone: "", noc: "FGTR" },
    { id: 11023, name: "Bee Network", url: "https://www.traveline.info", phone: "", noc: "BNDB" },
    { id: 11056, name: "Bee Network", url: "https://www.traveline.info", phone: "", noc: "BNVB" },
    { id: 11122, name: "Bee Network", url: "https://www.traveline.info", phone: "", noc: "BNGN" },
    { id: 11188, name: "Aberdeenshire Council", url: "https://www.traveline.info", phone: "", noc: "ABDC" },
    { id: 11189, name: "J R Services", url: "https://www.traveline.info", phone: "", noc: "JURG" },
    { id: 11386, name: "Swans Travel Ltd", url: "https://www.traveline.info", phone: "", noc: "SWTL" },
    { id: 11518, name: "Kent College", url: "https://www.traveline.info", phone: "", noc: "KCOL" },
    { id: 11584, name: "Thompsons Coaches", url: "https://www.traveline.info", phone: "", noc: "TMPC" },
    { id: 11782, name: "Bright Bus", url: "https://www.traveline.info", phone: "", noc: "BRBU" },
    { id: 11816, name: "Replacement Service", url: "https://www.traveline.info", phone: "", noc: "RRS" },
    { id: 11947, name: "Masons Coach Hire", url: "https://www.traveline.info", phone: "", noc: "MACH" },
    { id: 11949, name: "Golden Tours", url: "https://www.traveline.info", phone: "", noc: "GTSL" },
    { id: 11950, name: "Coopers Tours", url: "https://www.traveline.info", phone: "", noc: "CPTR" },
    { id: 11952, name: "Duck Tours", url: "https://www.traveline.info", phone: "", noc: "DUCK" },
    { id: 11953, name: "Hedge The Distance", url: "https://www.traveline.info", phone: "", noc: "HEDG" },
    { id: 11955, name: "Sweyne Coaches", url: "https://www.traveline.info", phone: "", noc: "LEWO" },
    { id: 11957, name: "Fargo Coaches", url: "https://www.traveline.info", phone: "", noc: "FARG" },
    { id: 11958, name: "Taylors Coach Travel", url: "https://www.traveline.info", phone: "", noc: "TCAT" },
    { id: 11959, name: "Carlone Ltd", url: "https://www.traveline.info", phone: "", noc: "CNLB" },
    {
        id: 11981,
        name: "Nottingham Minibuses and Coaches Ltd",
        url: "https://www.traveline.info",
        phone: "",
        noc: "PVRN",
    },
    { id: 12013, name: "Faversham Hopper", url: "https://www.traveline.info", phone: "", noc: "FVTC" },
    { id: 12079, name: "Woody's Taxis", url: "https://www.traveline.info", phone: "", noc: "WBWK" },
    {
        id: 12112,
        name: "Stagecoach East Midlands",
        url: "https://www.traveline.info",
        phone: "",
        noc: "SCEM",
    },
    { id: 12113, name: "Carolean Coaches", url: "https://www.traveline.info", phone: "", noc: "CRLN" },
    { id: 12178, name: "Finestyle Coaches", url: "https://www.traveline.info", phone: "", noc: "SLCH" },
    { id: 12211, name: "Eazy Coach Hire", url: "https://www.traveline.info", phone: "", noc: "EAZY" },
    {
        id: 12244,
        name: "Troopers Lodge Motor Services",
        url: "https://www.traveline.info",
        phone: "",
        noc: "TLGA",
    },
    { id: 12343, name: "James Bevan", url: "https://www.traveline.info", phone: "", noc: "JBVN" },
    { id: 12376, name: "Bee Network", url: "https://www.traveline.info", phone: "", noc: "BNFM" },
    {
        id: 12409,
        name: "Kirkstone Bathrooms, Tiles & Shutters Limited",
        url: "https://www.traveline.info",
        phone: "",
        noc: "KBTS",
    },
    { id: 12475, name: "Stagecoach South", url: "https://www.traveline.info", phone: "", noc: "SCSO" },
    { id: 12543, name: "Gwent Vales", url: "https://www.traveline.info", phone: "", noc: "GVTL" },
    {
        id: 12544,
        name: "Oxfordshire County Council (Fleet Services)",
        url: "https://www.traveline.info",
        phone: "",
        noc: "OXFC",
    },
    { id: 12574, name: "21 Transport", url: "https://www.traveline.info", phone: "", noc: "TWET" },
    {
        id: 12607,
        name: "Wilkins Travel (Port Talbot)",
        url: "https://www.traveline.info",
        phone: "",
        noc: "WILK",
    },
    { id: 12640, name: "Viscount Travel", url: "https://www.traveline.info", phone: "", noc: "VCTL" },
    { id: 12706, name: "Sunbeam Luxury Coaches", url: "https://www.traveline.info", phone: "", noc: "SUNB" },
    { id: 12739, name: "Premier Coaches", url: "https://www.traveline.info", phone: "", noc: "PREC" },
    {
        id: 12838,
        name: "National Express Accessible Transport",
        url: "https://www.traveline.info",
        phone: "",
        noc: "NEAT",
    },
    { id: 12904, name: "Nottingham Minibuses", url: "https://www.traveline.info", phone: "", noc: "NTMC" },
    { id: 12971, name: "Liberty Coaches", url: "https://www.traveline.info", phone: "", noc: "LICO" },
];
