export enum SourceType {
    directReport = "directReport",
    email = "email",
    phone = "phone",
    fax = "fax",
    post = "post",
    feed = "feed",
    radio = "radio",
    tv = "tv",
    web = "web",
    pager = "pager",
    text = "text",
    other = "other",
}

export enum Progress {
    draft = "draft",
    approvedDraft = "approvedDraft",
    open = "open",
    published = "published",
    closing = "closing",
    closed = "closed",
}

export enum MiscellaneousReason {
    unknown = "unknown",
    previousDisturbances = "previousDisturbances",
    incident = "incident",
    nearMiss = "nearMiss",
    safetyViolation = "safetyViolation",
    signalPassedAtDanger = "signalPassedAtDanger",
    stationOverrun = "stationOverrun",
    trainDoor = "trainDoor",
    emergencyServicesCall = "emergencyServicesCall",
    bombExplosion = "bombExplosion",
    securityAlert = "securityAlert",
    policeRequest = "policeRequest",
    fireBrigadeSafetyChecks = "fireBrigadeSafetyChecks",
    unattendedBag = "unattendedBag",
    telephonedThreat = "telephonedThreat",
    suspectVehicle = "suspectVehicle",
    civilEmergency = "civilEmergency",
    airRaid = "airRaid",
    sabotage = "sabotage",
    bombAlert = "bombAlert",
    attack = "attack",
    evacuation = "evacuation",
    terroristIncident = "terroristIncident",
    gunfireOnRoadway = "gunfireOnRoadway",
    explosion = "explosion",
    explosionHazard = "explosionHazard",
    securityIncident = "securityIncident",
    fireBrigadeOrder = "fireBrigadeOrder",
    policeActivity = "policeActivity",
    fire = "fire",
    linesideFire = "linesideFire",
    vandalism = "vandalism",
    passengerAction = "passengerAction",
    staffAssault = "staffAssault",
    railwayCrime = "railwayCrime",
    assault = "assault",
    theft = "theft",
    altercation = "altercation",
    illVehicleOccupants = "illVehicleOccupants",
    accident = "accident",
    fatality = "fatality",
    personUnderTrain = "personUnderTrain",
    personHitByTrain = "personHitByTrain",
    personIllOnVehicle = "personIllOnVehicle",
    emergencyServices = "emergencyServices",
    collision = "collision",
    overcrowded = "overcrowded",
    insufficientDemand = "insufficientDemand",
    lightingFailure = "lightingFailure",
    leaderBoardFailure = "leaderBoardFailure",
    serviceIndicatorFailure = "serviceIndicatorFailure",
    serviceFailure = "serviceFailure",
    operatorCeasedTrading = "operatorCeasedTrading",
    operatorSuspended = "operatorSuspended",
    congestion = "congestion",
    routeBlockage = "routeBlockage",
    personOnTheLine = "personOnTheLine",
    vehicleOnTheLine = "vehicleOnTheLine",
    levelCrossingIncident = "levelCrossingIncident",
    objectOnTheLine = "objectOnTheLine",
    fallenTreeOnTheLine = "fallenTreeOnTheLine",
    vegetation = "vegetation",
    trainStruckAnimal = "trainStruckAnimal",
    trainStruckObject = "trainStruckObject",
    animalOnTheLine = "animalOnTheLine",
    routeDiversion = "routeDiversion",
    roadClosed = "roadClosed",
    roadworks = "roadworks",
    sewerageMaintenance = "sewerageMaintenance",
    roadMaintenance = "roadMaintenance",
    asphalting = "asphalting",
    paving = "paving",
    specialEvent = "specialEvent",
    march = "march",
    procession = "procession",
    demonstration = "demonstration",
    publicDisturbance = "publicDisturbance",
    filterBlockade = "filterBlockade",
    sightseersObstructingAccess = "sightseersObstructingAccess",
    holiday = "holiday",
    bridgeStrike = "bridgeStrike",
    viaductFailure = "viaductFailure",
    overheadObstruction = "overheadObstruction",
    undefinedProblem = "undefinedProblem",
    problemsAtBorderPost = "problemsAtBorderPost",
    problemsAtCustomsPost = "problemsAtCustomsPost",
    speedRestrictions = "speedRestrictions",
    logisticProblems = "logisticProblems",
    problemsOnLocalRoad = "problemsOnLocalRoad",
}

export enum PersonnelReason {
    unknown = "unknown",
    staffSickness = "staffSickness",
    staffInjury = "staffInjury",
    contractorStaffInjury = "contractorStaffInjury",
    staffAbsence = "staffAbsence",
    staffInWrongPlace = "staffInWrongPlace",
    staffShortage = "staffShortage",
    industrialAction = "industrialAction",
    unofficialIndustrialAction = "unofficialIndustrialAction",
    workToRule = "workToRule",
    undefinedPersonnelProblem = "undefinedPersonnelProblem",
}

export enum EquipmentReason {
    unknown = "unknown",
    pointsProblem = "pointsProblem",
    pointsFailure = "pointsFailure",
    signalProblem = "signalProblem",
    trainWarningSystemProblem = "trainWarningSystemProblem",
    trackCircuitProblem = "trackCircuitProblem",
    signalFailure = "signalFailure",
    signalAndSwitchFailure = "signalAndSwitchFailure",
    derailment = "derailment",
    engineFailure = "engineFailure",
    tractionFailure = "tractionFailure",
    breakDown = "breakDown",
    technicalProblem = "technicalProblem",
    brokenRail = "brokenRail",
    poorRailConditions = "poorRailConditions",
    wheelImpactLoad = "wheelImpactLoad",
    lackOfOperationalStock = "lackOfOperationalStock",
    defectiveFireAlarmEquipment = "defectiveFireAlarmEquipment",
    defectivePlatformEdgeDoors = "defectivePlatformEdgeDoors",
    defectiveCctv = "defectiveCctv",
    defectivePublicAnnouncementSystem = "defectivePublicAnnouncementSystem",
    ticketingSystemNotAvailable = "ticketingSystemNotAvailable",
    leveCrossingFailure = "leveCrossingFailure",
    repairWork = "repairWork",
    constructionWork = "constructionWork",
    maintenanceWork = "maintenanceWork",
    emergencyEngineeringWork = "emergencyEngineeringWork",
    lateFinishToEngineeringWork = "lateFinishToEngineeringWork",
    powerProblem = "powerProblem",
    oveheadWireFailure = "oveheadWireFailure",
    fuelProblem = "fuelProblem",
    swingBridgeFailure = "swingBridgeFailure",
    escalatorFailure = "escalatorFailure",
    liftFailure = "liftFailure",
    gangwayProblem = "gangwayProblem",
    closedForMaintenance = "closedForMaintenance",
    fuelShortage = "fuelShortage",
    deicingWork = "deicingWork",
    wheelProblem = "wheelProblem",
    slipperyTrack = "slipperyTrack",
    luggageCarouselProblem = "luggageCarouselProblem",
    undefinedEquipmentProblem = "undefinedEquipmentProblem",
}

export enum EnvironmentReason {
    unknown = "unknown",
    fog = "fog",
    roughSea = "roughSea",
    heavySnowFall = "heavySnowFall",
    driftingSnow = "driftingSnow",
    blizzardConditions = "blizzardConditions",
    heavyRain = "heavyRain",
    strongWinds = "strongWinds",
    stormConditions = "stormConditions",
    stormDamage = "stormDamage",
    tidalRestrictions = "tidalRestrictions",
    highTide = "highTide",
    lowTide = "lowTide",
    ice = "ice",
    slipperiness = "slipperiness",
    iceDrift = "iceDrift",
    glazedFrost = "glazedFrost",
    frozen = "frozen",
    hail = "hail",
    sleet = "sleet",
    highTemperatures = "highTemperatures",
    flooding = "flooding",
    waterlogged = "waterlogged",
    lowWaterLevel = "lowWaterLevel",
    highWaterLevel = "highWaterLevel",
    fallenLeaves = "fallenLeaves",
    fallenTree = "fallenTree",
    landslide = "landslide",
    undefinedEnvironmentalProblem = "undefinedEnvironmentalProblem",
    lightningStrike = "lightningStrike",
    sewerOverflow = "sewerOverflow",
    grassFire = "grassFire",
}

export enum DayType {
    unknown = "unknown",
    monday = "monday",
    tuesday = "tuesday",
    wednesday = "wednesday",
    thursday = "thursday",
    friday = "friday",
    saturday = "saturday",
    sunday = "sunday",
    weekdays = "weekdays",
    weekends = "weekends",
    holiday = "holiday",
    publicHoliday = "publicHoliday",
    religiousHoliday = "religiousHoliday",
    federalHoliday = "federalHoliday",
    regionalHoliday = "regionalHoliday",
    nationalHoliday = "nationalHoliday",
    mondayToFriday = "mondayToFriday",
    mondayToSaturday = "mondayToSaturday",
    sundaysAndPublicHolidays = "sundaysAndPublicHolidays",
    schoolDays = "schoolDays",
    everyDay = "everyDay",
    undefinedDayType = "undefinedDayType",
}

export enum VehicleMode {
    air = "air",
    bus = "bus",
    coach = "coach",
    ferry = "ferry",
    metro = "metro",
    rail = "rail",
    tram = "tram",
    underground = "underground",
}

export enum Severity {
    unknown = "unknown",
    verySlight = "verySlight",
    slight = "slight",
    normal = "normal",
    severe = "severe",
    verySevere = "verySevere",
    noImpact = "noImpact",
    undefined = "undefined",
}

export enum Condition {
    unknown = "unknown",
    altered = "altered",
    cancelled = "cancelled",
    delayed = "delayed",
    diverted = "diverted",
    noService = "noService",
    disrupted = "disrupted",
    additionalService = "additionalService",
    specialService = "specialService",
    onTime = "onTime",
    normalService = "normalService",
    intermittentService = "intermittentService",
    shortFormedService = "shortFormedService",
    fullLengthService = "fullLengthService",
    extendedService = "extendedService",
    splittingTrain = "splittingTrain",
    replacementTransport = "replacementTransport",
    arrivesEarly = "arrivesEarly",
    shuttleService = "shuttleService",
    replacementService = "replacementService",
    undefinedServiceInformation = "undefinedServiceInformation",
}

export enum StopPointType {
    unknown = "unknown",
    platformNumber = "platformNumber",
    terminalGate = "terminalGate",
    ferryBerth = "ferryBerth",
    harbourPier = "harbourPier",
    landingStage = "landingStage",
    busStop = "busStop",
    undefinedBookingInformation = "undefinedBookingInformation",
}

export enum RoutePointType {
    unknown = "unknown",
    startPoint = "startPoint",
    destination = "destination",
    stop = "stop",
    via = "via",
    notStopping = "notStopping",
    temporaryStop = "temporaryStop",
    temporarilyNotStopping = "temporarilyNotStopping",
    exceptionalStop = "exceptionalStop",
    additionalStop = "additionalStop",
    requestStop = "requestStop",
    frontTrainDestination = "frontTrainDestination",
    rearTrainDestination = "rearTrainDestination",
    throughServiceDestination = "throughServiceDestination",
    notVia = "notVia",
    alteredStartPoint = "alteredStartPoint",
    alteredDestination = "alteredDestination",
    undefinedRoutePoint = "undefinedRoutePoint",
    cancelled = "cancelled",
    normalService = "normalService", // This and cancelled are not allowed by the xsd but are used by some providers so need to be converted
}

export enum FacilityStatus {
    unknown = "unknown",
    available = "available",
    notAvailable = "notAvailable",
    partiallyAvailable = "partiallyAvailable",
    added = "added",
    removed = "removed",
}

export enum InterchangeStatus {
    unknown = "unknown",
    connection = "connection",
    replacement = "replacement",
    alternative = "alternative",
    connectionNotHeld = "connectionNotHeld",
    connectionHeld = "connectionHeld",
    statusOfConenctionUndecided = "statusOfConenctionUndecided",
    undefinedCrossReferenceInformation = "undefinedCrossReferenceInformation",
}

export enum CallStatus {
    onTime = "onTime",
    early = "early",
    delayed = "delayed",
    cancelled = "cancelled",
    arrived = "arrived",
    departed = "departed",
    missed = "missed",
    noReport = "noReport",
    notExpected = "notExpected",
}

export enum ArrivalBoardingActivity {
    alighting = "alighting",
    noAlighting = "noAlighting",
    passThru = "passThru",
}

export enum DepartureBoardingActivity {
    boarding = "boarding",
    noBoarding = "noBoarding",
    passThru = "passThru",
}
