FROM public.ecr.aws/lambda/nodejs:22-arm64

ARG FUNCTION_DIR
ARG SERVICE_NAME

RUN ["dnf", "install", "-y", "libxml2", "unzip"]
ADD ["${SERVICE_NAME}.zip", "${LAMBDA_TASK_ROOT}"]
RUN unzip ${LAMBDA_TASK_ROOT}/${SERVICE_NAME}.zip && rm -rf ${LAMBDA_TASK_ROOT}/${SERVICE_NAME}.zip

CMD ["index.handler"]
