name: Auto-update PR Branches

on:
  push: {}

jobs:
  autoupdate:
    name: autoupdate
    runs-on: ubuntu-22.04
    permissions:
      pull-requests: write
    steps:
      - uses: docker://chinthakagodawita/autoupdate-action:v1
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - run: echo 'Merge conflicts found!'
        if: ${{ steps.autoupdate.outputs.conflicted }}

      - run: echo 'No merge conflicts'
        if: ${{ !steps.autoupdate.outputs.conflicted }}
