name: Check PR (called workflow)

on:
  pull_request:

permissions:
  id-token: write # This is required for aws oidc connection
  contents: read # This is required for actions/checkout
  pull-requests: write # This is required for posting comment to PR

env:
  TERRAFORM_VERSION: 1.6.6
  HUSKY: 0
  TZ: "Europe/London"

jobs:
  lint_pr_title:
    name: Lint PR title
    runs-on: ubuntu-24.04
    steps:
      - uses: amannn/action-semantic-pull-request@48f256284bd46cdaab1048c3721360e808335d50 # v6.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  lint_and_test_functions:
    runs-on: ubuntu-24.04
    name: Lint code and run unit tests
    steps:
      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Setup node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: "24.x"

      - name: Install pnpm
        uses: pnpm/action-setup@0e279bb959325dab635dd2c09392533439d90093 # v6.0.8
        with:
          run_install: false

      - name: Get pnpm store directory
        run: echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('src/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: make install-deps

      - name: Run Typescript build
        run: make check-types

      - name: Lint code
        run: make lint-functions

      - name: Run unit test
        run: make test-functions

  check_for_function_changes:
    uses: ./.github/workflows/get_directories_with_changes.yaml
    name: Get list of updated functions
    needs:
      - lint_and_test_functions
    with:
      path: "./src/functions"
      shared_code_path: "./src/shared"

  zip_functions:
    uses: ./.github/workflows/zip_function.yaml
    name: Zip functions
    if: ${{ needs.check_for_function_changes.outputs.changed_directories }}
    strategy:
      matrix:
        dir: ${{ fromJSON(needs.check_for_function_changes.outputs.changed_directories) }}
    needs:
      - check_for_function_changes
    with:
      function_dir: ${{ matrix.dir }}

  terraform_plan:
    runs-on: ubuntu-24.04
    name: Terraform plan
    needs:
      - check_for_function_changes
      - zip_functions
    if: ${{ always() && !cancelled() && needs.check_for_function_changes.result == 'success' }}
    defaults:
      run:
        working-directory: ./terraform
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    environment: dev
    steps:
      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Download zipped functions
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          path: ./src/functions/dist
          merge-multiple: true

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@e7f100cf4c008499ea8adda475de1042d6975c7b # v6.2.0
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE }}
          aws-region: ${{ vars.AWS_DEFAULT_REGION }}
          role-session-name: GitHub-OIDC-TERRAFORM

      - name: Cache Terraform tflint plugin
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: ~/.tflint.d/plugins
          key: dev-tflint-${{ hashFiles('terraform/.tflint.hcl') }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e # v4.0.1
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Run Terraform fmt
        run: terraform fmt -check -recursive

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@b480b8fcdaa6f2c577f8e4fa799e89e756bb7c93 # v6.2.2
        with:
          tflint_wrapper: true

      - name: Init TFLint
        run: tflint --init

      - name: Run TFLint
        run: tflint --recursive --config "$(pwd)/.tflint.hcl" -f compact --minimum-failure-severity=warning

      - name: Terraform init
        run: terraform -chdir=dev init

      - name: Terraform validate
        run: terraform -chdir=dev validate -no-color

      - name: Terraform plan
        run: terraform -chdir=dev plan -lock-timeout=5m -input=false -no-color -out .planfile

      - name: Post PR comment with Terraform plan
        uses: borchero/terraform-plan-comment@2d41e908725447b1677913001dfb92fa7010c025 # v3.1.0
        with:
          token: ${{ github.token }}
          working-directory: ./terraform/dev
          planfile: .planfile
        continue-on-error: true
