on:
  workflow_dispatch:
    inputs:
      is_hotfix:
        type: boolean
        description: Release hotfix? If checked, creates a draft hotfix release

name: Create Draft Release

jobs:
  create_draft_release:
    runs-on: ubuntu-22.04
    name: ${{ inputs.is_hotfix && 'Create Hotfix Draft Release' || 'Create Draft Release' }}
    permissions:
      contents: write

    steps:
      - name: Bump version
        id: get_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dry_run: true

      - name: Push tag
        id: push_tag
        uses: rickstaa/action-create-tag@v1.7.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag: v${{steps.get_version.outputs.new_version}}${{ inputs.is_hotfix && '-hotfix' || '' }}

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{steps.get_version.outputs.new_version}}${{ inputs.is_hotfix && '-hotfix' || '' }}
          name: Release v${{steps.get_version.outputs.new_version}}${{ inputs.is_hotfix && '-hotfix' || '' }}
          body: ${{ steps.get_version.outputs.changelog }}
          draft: true
