on:
  workflow_dispatch:
    inputs:
      is_hotfix:
        type: boolean
        description: Release hotfix? If checked, creates a draft hotfix release

name: Create Draft Release

jobs:
  create_draft_release:
    runs-on: ubuntu-22.04
    name: ${{ inputs.is_hotfix && 'Create Hotfix Draft Release' || 'Create Draft Release' }}
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Get Next Version
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref_name }}

      - name: Bump version
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: v${{ steps.semver.outputs.next }}${{ inputs.is_hotfix && '-hotfix' || '' }}

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{steps.tag_version.outputs.new_tag}}
          name: Release v${{ steps.semver.outputs.next }}${{ inputs.is_hotfix && '-hotfix' || '' }}
          body: ${{ steps.tag_version.outputs.changelog }}
          draft: true
