name: Create draft release

env:
  TERRAFORM_VERSION: 1.6.6

on:
  workflow_dispatch:
    inputs:
      is_hotfix:
        type: boolean
        description: Create as hotfix draft release
jobs:
  create_draft_release:
    runs-on: ubuntu-24.04
    name: ${{ inputs.is_hotfix && 'Create Hotfix Draft Release' || 'Create Draft Release' }}
    permissions:
      contents: write # This is required to create the release
      id-token: write # This is required for aws oidc connection
    environment: prod
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE }}
          aws-region: ${{ vars.AWS_DEFAULT_REGION }}
          role-session-name: GitHub-OIDC-TERRAFORM

      - name: Terraform init
        run: terraform -chdir=terraform/prod init

      - name: Terraform plan
        run: terraform -chdir=terraform/prod plan -lock-timeout=5m -input=false -no-color

      - name: Bump version
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          name: ${{ steps.tag_version.outputs.new_tag }}${{ inputs.is_hotfix && ' (hotfix)' || '' }}
          body: ${{ steps.tag_version.outputs.changelog }}
          draft: true
