on:
  workflow_dispatch:
    inputs:
      is_hotfix:
        type: boolean
        description: Release hotfix? If checked, creates a draft hotfix release

name: Create Draft Release

jobs:
  create_draft_release:
    runs-on: ubuntu-22.04
    name: ${{ inputs.is_hotfix && 'Create Hotfix Draft Release' || 'Create Draft Release' }}
    permissions:
      contents: write

    steps:
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          append_to_pre_release_tag: ${{ inputs.is_hotfix && 'hotfix' || undefined }}

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
          draft: true
