name: Deploy (test)

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write # This is required for aws oidc connection
  contents: read # This is required for actions/checkout

jobs:
  deploy:
    uses: ./.github/workflows/deploy_code.yaml
    with:
      stage: test
      deploy_all_functions: ${{ github.event_name == 'workflow_dispatch' }}
    secrets: inherit

  run_integration_tests:
    uses: ./.github/workflows/run_integration_tests.yaml
    name: Run integration tests
    needs:
      - deploy
    if: ${{ always() && !cancelled() && needs.deploy.result == 'success' }}
    with:
      stage: test
    secrets: inherit
