run-name: Deploy (${{ inputs.stage }})

on:
  workflow_call:
    inputs:
      stage:
        required: true
        type: string

permissions:
  id-token: write # This is required for aws oidc connection
  contents: read # This is required for actions/checkout

env:
  TERRAFORM_VERSION: 1.6.6

jobs:
  check_for_function_changes:
    uses: ./.github/workflows/get_directories_with_changes.yaml
    name: Get list of updated functions
    with:
      path: "./src/functions"
      shared_code_path: "./src/shared"

  zip_functions:
    uses: ./.github/workflows/zip_function.yaml
    name: Zip updated functions
    if: ${{ needs.check_for_function_changes.outputs.changed_directories }}
    strategy:
      matrix:
        dir: ${{ fromJson(needs.check_for_function_changes.outputs.changed_directories) }}
    needs:
      - check_for_function_changes
    with:
      function_dir: ${{ matrix.dir }}

  deploy_functions_and_infrastructure:
    runs-on: ubuntu-latest
    name: Deploy functions and infrastructure
    env:
      STAGE: ${{ inputs.stage }}
    environment: ${{ inputs.stage }}
    needs:
      - check_for_function_changes
      - zip_functions
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9
          run_install: false

      - name: Get pnpm store directory
        run: echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('src/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Download zipped functions
        uses: actions/download-artifact@v4
        with:
          path: ./src/functions/dist
          merge-multiple: true

      - name: Install dependencies
        working-directory: ./src
        run: pnpm install

      - name: Build all functions
        working-directory: ./src
        run: pnpm build-all

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE }}
          aws-region: ${{ vars.AWS_DEFAULT_REGION }}
          role-session-name: GitHub-OIDC-TERRAFORM

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Terraform init
        run: terraform -chdir=terraform/${{ inputs.stage }} init

      - name: Terraform plan
        run: terraform -chdir=terraform/${{ inputs.stage }} plan -lock-timeout=5m -input=false -no-color -out .planfile

      - name: Terraform apply
        if: steps.plan.outcome == 'success'
        run: terraform -chdir=terraform/${{ inputs.stage }} apply -lock-timeout=5m -input=false -no-color .planfile

      - name: Run database migrations
        run: |
          aws lambda invoke --function-name integrated-data-db-migrator-migrate-${{ inputs.stage }} --cli-binary-format raw-in-base64-out response.json

      - name: Get list of ECS tasks
        id: get_ecs_tasks
        run: echo "ecs_tasks=\"$(cd ./src/tasks && ls -d */ | sed 's#/##' | jq -R | jq -sc | sed 's/"/\\"/g')\"" >> "$GITHUB_OUTPUT"

  deploy_ecs_tasks:
    uses: ./.github/workflows/deploy_ecs_task.yaml
    name: Deploy ECS tasks
    strategy:
      matrix:
        dir: ${{ fromJson(needs.deploy_functions_and_infrastructure.outputs.ecs_tasks) }}
    needs:
      - deploy_functions_and_infrastructure
    with:
      stage: ${{ inputs.stage }}
      task_name: ${{ matrix.dir }}
    secrets: inherit
