on:
  pull_request_review:
    types: [submitted]

env:
  TERRAFORM_VERSION: 1.6.6
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  HUSKY: 0

jobs:
  deploy:
    uses: ./.github/workflows/deploy_code.yaml
    if: github.event.review.state == 'approved' && github.event.pull_request.base.ref == 'main'
    with:
      stage: dev
    secrets: inherit

  run_integration_tests:
    uses: ./.github/workflows/run_integration_tests.yaml
    name: Run integration tests
    needs:
      - deploy
    if: ${{ always() && !cancelled() && needs.deploy.result == 'success' }}
    with:
      stage: dev
    secrets: inherit
