on:
  push:
    branches:
      - main

name: Terraform Apply Test

permissions:
  id-token: write # This is required for aws oidc connection
  contents: read # This is required for actions/checkout.

env:
  TERRAFORM_VERSION: 1.6.6
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  HUSKY: 0

jobs:
  check_for_function_changes:
    uses: ./.github/workflows/get_directories_with_changes.yaml
    name: Get list of updated functions
    with:
      path: "./src/functions"
      shared_code_path: "./src/shared"

  check_for_task_changes:
    uses: ./.github/workflows/get_directories_with_changes.yaml
    name: Check for ECS task changes
    with:
      path: "./src/tasks"
      shared_code_path: "./src/shared"

  zip_functions:
    uses: ./.github/workflows/zip_function.yaml
    name: Zip updated functions
    if: ${{ needs.check_for_function_changes.outputs.changed_directories }}
    strategy:
      matrix:
        dir: ${{ fromJson(needs.check_for_function_changes.outputs.changed_directories) }}
    needs:
      - check_for_function_changes
    with:
      function_dir: ${{ matrix.dir }}

  terraform_apply:
    uses: ./.github/workflows/terraform_apply.yaml
    name: Terraform Apply Test
    needs:
      - check_for_function_changes
      - zip_functions
    if: ${{ always() && !cancelled() && needs.check_for_function_changes.result == 'success' }}
    with:
      stage: "test"
      terraform_version: 1.6.6
      use_artifacts: true
    secrets: inherit

  deploy_ecs_tasks:
    uses: ./.github/workflows/deploy_ecs_manual.yaml
    name: Deploy ECS tasks
    if: ${{ needs.check_for_task_changes.outputs.changed_directories }}
    strategy:
      matrix:
        dir: ${{ fromJson(needs.check_for_task_changes.outputs.changed_directories) }}
    needs:
      - check_for_task_changes
      - terraform_apply
    with:
      stage: "test"
      task: ${{ matrix.dir }}
    secrets: inherit

  run_integration_tests:
    uses: ./.github/workflows/run_integration_tests.yaml
    name: Run Integration Tests - Test
    needs:
      - terraform_apply
    if: ${{ always() && !cancelled() && needs.terraform_apply.result == 'success' }}
    with:
      stage: "test"
    secrets: inherit
