on:
  workflow_dispatch:
    inputs:
      stage:
        type: environment
        description: Environment to deploy to

name: Terraform Apply (All Functions)

permissions:
  id-token: write # This is required for aws oidc connection
  contents: read # This is required for actions/checkout.

env:
  TERRAFORM_VERSION: 1.6.6
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  HUSKY: 0

jobs:
  terraform_apply:
    uses: ./.github/workflows/terraform_apply.yaml
    name: Terraform Apply - ${{ inputs.stage }}
    with:
      stage: ${{ inputs.stage }}
      terraform_version: 1.6.6
      use_artifacts: false
    secrets: inherit
