on:
  pull_request_review:
    types: [submitted]
  workflow_dispatch:

name: Terraform Apply Dev

permissions:
  id-token: write # This is required for aws oidc connection
  contents: read # This is required for actions/checkout.

env:
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  HUSKY: 0

jobs:
  check_for_function_changes:
    uses: ./.github/workflows/get_directories_with_changes.yaml
    name: Get list of updated functions
    if: (github.event.review.state == 'approved' && github.event.pull_request.base.ref == 'main') || github.event_name == 'workflow_dispatch'
    with:
      path: "./src/tasks"

  build_and_deploy_ecs_tasks:
    uses: ./.github/workflows/deploy_ecs_task_shared_services.yaml
    name: Update cluster with updated
    if: ${{ needs.check_for_function_changes.outputs.changed_directories }}
    strategy:
      matrix: ${{fromJson(needs.check_for_function_changes.outputs.changed_directories)}}
    needs:
      - check_for_function_changes
    with:
      task_dir: ${{ matrix.dir }}
    secrets:
      oidc_role_arn: ${{ secrets.AWS_OIDC_ROLE_DEV }}

