on:
  pull_request_review:
    types: [submitted]
  workflow_dispatch:

name: Terraform Apply Dev

permissions:
  id-token: write # This is required for aws oidc connection
  contents: read # This is required for actions/checkout.

env:
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  HUSKY: 0

jobs:
  check_for_function_changes:
    uses: ./.github/workflows/get_directories_with_changes.yaml
    name: Check for lambda function changes
    if: (github.event.review.state == 'approved' && github.event.pull_request.base.ref == 'main') || github.event_name == 'workflow_dispatch'
    with:
      path: "./src/functions"
      directories_only: true

  check_for_shared_code_changes:
    uses: ./.github/workflows/get_directories_with_changes.yaml
    name: Check for shared code changes
    if: (github.event.review.state == 'approved' && github.event.pull_request.base.ref == 'main') || github.event_name == 'workflow_dispatch'
    with:
      path: "./src/shared"

  check_for_task_changes:
    uses: ./.github/workflows/get_directories_with_changes.yaml
    name: Check for ECS task changes
    if: (github.event.review.state == 'approved' && github.event.pull_request.base.ref == 'main') || github.event_name == 'workflow_dispatch'
    with:
      path: "./src/tasks"

  zip_functions:
    uses: ./.github/workflows/zip_function.yaml
    name: Zip updated functions
    if: ${{ needs.check_for_function_changes.outputs.changed_files_count != 0 || needs.check_for_shared_code_changes.outputs.changed_files_count != 0 }}
    strategy:
      matrix:
        dir: ${{ fromJson(needs.check_for_shared_code_changes.outputs.changed_files_count != 0 && $(ls -d ./src/functions/*/ | jq -R | jq -s) || needs.check_for_function_changes.outputs.changed_directories) }}
    needs:
      - check_for_function_changes
      - check_for_shared_code_changes
    with:
      function_dir: ${{ matrix.dir }}

  terraform_apply:
    uses: ./.github/workflows/terraform_apply.yaml
    name: Terraform Apply Dev
    needs:
      - check_for_function_changes
      - check_for_shared_code_changes
      - zip_functions
    if: ${{ always() && !cancelled() && needs.check_for_function_changes.result == 'success' && needs.check_for_shared_code_changes.result == 'success' }}
    with:
      stage: "dev"
      terraform_version: 1.6.6
      use_artifacts: true
    secrets: inherit

  deploy_ecs_tasks:
    uses: ./.github/workflows/deploy_ecs_manual.yaml
    name: Deploy ECS tasks
    if: ${{ needs.check_for_task_changes.outputs.changed_files_count != 0 || needs.check_for_shared_code_changes.outputs.changed_files_count != 0 }}
    strategy:
      matrix:
        dir: ${{ fromJson(needs.check_for_shared_code_changes.outputs.changed_files_count != 0 && $(ls -d ./src/tasks/*/ | jq -R | jq -s) || needs.check_for_task_changes.outputs.changed_directories) }}
    needs:
      - check_for_shared_code_changes
      - check_for_task_changes
      - terraform_apply
    with:
      stage: "dev"
      task: ${{ matrix.dir }}
    secrets: inherit

  run_integration_tests:
    uses: ./.github/workflows/run_integration_tests.yaml
    name: Run Integration Tests - Dev
    needs:
      - terraform_apply
    if: ${{ always() && !cancelled() && needs.terraform_apply.result == 'success' }}
    with:
      stage: "dev"
    secrets: inherit
