name: ECR Push

on:
  workflow_call:
    inputs:
      task_name:
        type: string
        required: true
      branch:
        type: string
        required: true
    secrets:
      AWS_OIDC_ROLE:
        required: true
    outputs:
      image:
        value: ${{ jobs.ecr_push.outputs.image }}

jobs:
  ecr_push:
    runs-on: ubuntu-22.04
    name: Push to ECR
    outputs:
      image: ${{ steps.image_tag.outputs.image }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE }}
          aws-region: "eu-west-2"
          role-session-name: GitHub-OIDC-Shared-Services

      - name: Login to Amazon ECR
        id: login_ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Get image tag
        id: image_tag
        run: |
          echo "image=${{ steps.login_ecr.outputs.registry }}/${{ inputs.task_name }}:$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./src
          platforms: linux/arm64
          push: true
          tags: ${{ steps.image_tag.outputs.image }}
          build-args: servicePath=${{ inputs.task_name }}
