on:
  push:
    branches:
      - main

name: Generate Docs for Terraform Modules

defaults:
    run:
        working-directory: ./terraform

permissions:
    contents: write # This is required for terraform-docs to push READMEs back to PR branch
    pull-requests: write # This is required for posting comment to PR

jobs:
    generate_docs_for_modules:
      name: "Generate terraform docs for modules"
      runs-on: ubuntu-22.04
      steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
            ref: ${{ github.event.pull_request.head.ref }}
            token: ${{ github.token }}


        - name: Run terraform-docs to generate README.md for modules
          shell: bash
          run: ./generate-terraform-docs.sh

        - name: Check if any updates have been made to the docs
          id: verify_diff
          run: |
            git diff --quiet . || echo "changed=true" >> $GITHUB_OUTPUT

        - name: Commit docs if changes have been made
          if: steps.verify_diff.outputs.changed == 'true'
          run: |
            git config --global user.name 'docs-bot'
            git config --global user.email 'docs-bot@users.noreply.github.com'
            git add "*README.md" 
            git commit -am "Automated module docs"
            git push