on:
  push:
    branches:
      - main

name: Generate Docs for Terraform Modules

defaults:
    run:
        working-directory: ./

permissions:
    contents: write # This is required for terraform-docs to push READMEs to main

jobs:
    generate_docs_for_modules:
      name: "Generate terraform docs for modules"
      runs-on: ubuntu-22.04
      steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
            ref: ${{ github.event.pull_request.head.ref }}
            token: ${{ github.token }}


        - name: Generate README.md for modules
          shell: bash
          run: ./scripts/generate-terraform-docs.sh

        - name: Check if any updates have been made to the docs
          id: verify_diff
          run: |
            git add "terraform/modules/*README.md" 
            git diff --quiet . || echo "changed=true" >> $GITHUB_OUTPUT
            git diff --staged --quiet . || echo "added=true" >> $GITHUB_OUTPUT

        - name: Commit docs if changes have been made
          if: steps.verify_diff.outputs.changed == 'true' || steps.verify_diff.outputs.added == 'true'
          run: |
            git config --global user.name 'bods-docs-bot'
            git config --global user.email 'bods-docs-bot@users.noreply.github.com'
            git commit -am "Automated module docs"
            git push