on:
  workflow_dispatch:
    inputs:
      stage:
        options:
          - dev
          - test
        type: choice
        description: Environment to run integration tests against

name: Run integration tests (manual)

permissions:
  id-token: write # This is required for aws oidc connection
  contents: read # This is required for actions/checkout.


env:
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

jobs:
  run_tests_on_dev:
    uses: ./.github/workflows/run_integration_tests.yaml
    name: Run Integration Tests - Dev
    if: inputs.stage == 'dev'
    with:
      stage: ${{ inputs.stage }}
    secrets:
      oidc_role_arn: ${{ secrets.AWS_OIDC_ROLE_DEV}}

  run_tests_on_test:
    uses: ./.github/workflows/run_integration_tests.yaml
    name: Run Integration Tests - Test
    if: inputs.stage == 'test'
    with:
      stage: ${{ inputs.stage }}
    secrets:
      oidc_role_arn: ${{ secrets.AWS_OIDC_ROLE_TEST}}
