on:
  workflow_dispatch:
    inputs:
      stage:
        type: environment
        description: Environment to run integration tests against

name: Run integration tests (manual)

permissions:
  id-token: write # This is required for aws oidc connection
  contents: read # This is required for actions/checkout.

env:
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

jobs:
  run_tests_on_dev:
    uses: ./.github/workflows/run_integration_tests.yaml
    name: Run Integration Tests - ${{ inputs.stage }}
    with:
      stage: ${{ inputs.stage }}
