on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment

name: Run integration tests (manual)

permissions:
  id-token: write # This is required for aws oidc connection
  contents: read # This is required for actions/checkout.

env:
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

jobs:
  run_tests:
    uses: ./.github/workflows/run_integration_tests.yaml
    name: Run Integration Tests - ${{ inputs.environment }}
    with:
      environment: ${{ inputs.environment }}
