on:
  pull_request:

permissions:
  id-token: write # This is required for aws oidc connection
  contents: read # This is required for actions/checkout
  pull-requests: write # This is required for posting comment to PR

env:
  TERRAFORM_VERSION: 1.6.6
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  HUSKY: 0
  TZ: "Europe/London"

jobs:
  lint-pr-title:
    name: Lint PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  lint_and_test_functions:
    runs-on: ubuntu-latest
    name: Lint code and run unit tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9
          run_install: false

      - name: Get pnpm store directory
        run: echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('src/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: make install-deps

      - name: Run Typescript build
        run: make check-types

      - name: Lint code
        run: make lint-functions

      - name: Run unit test
        run: make test-functions

  check_for_function_changes:
    uses: ./.github/workflows/get_directories_with_changes.yaml
    name: Get list of updated functions
    needs:
      - lint_and_test_functions
    with:
      path: "./src/functions"
      shared_code_path: "./src/shared"

  zip_functions:
    uses: ./.github/workflows/zip_function.yaml
    name: Zip updated functions
    if: ${{ needs.check_for_function_changes.outputs.changed_directories }}
    strategy:
      matrix:
        dir: ${{ fromJson(needs.check_for_function_changes.outputs.changed_directories) }}
    needs:
      - check_for_function_changes
    with:
      function_dir: ${{ matrix.dir }}

  terraform_plan:
    runs-on: ubuntu-latest
    name: Terraform plan
    needs:
      - check_for_function_changes
      - zip_functions
    if: ${{ always() && !cancelled() && needs.check_for_function_changes.result == 'success' }}
    defaults:
      run:
        working-directory: ./terraform
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download zipped functions
        uses: actions/download-artifact@v4
        with:
          path: ./src/functions/dist
          merge-multiple: true

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE }}
          aws-region: eu-west-2
          role-session-name: GitHub-OIDC-TERRAFORM

      - name: Cache Terraform tflint plugin
        uses: actions/cache@v4
        with:
          path: ~/.tflint.d/plugins
          key: dev-tflint-${{ hashFiles('terraform/.tflint.hcl') }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Run Terraform fmt
        run: terraform fmt -check -recursive

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_wrapper: true

      - name: Init TFLint
        run: tflint --init

      - name: Run TFLint
        run: tflint --recursive --config "$(pwd)/.tflint.hcl" -f compact --minimum-failure-severity=warning

      - name: Terraform init
        run: terraform -chdir=dev init

      - name: Terraform validate
        run: terraform -chdir=dev validate -no-color

      - name: Terraform plan
        run: terraform -chdir=dev plan -lock-timeout=5m -input=false -no-color -out .planfile

      - name: Post PR comment with Terraform plan
        uses: borchero/terraform-plan-comment@v1
        with:
          token: ${{ github.token }}
          working-directory: ./terraform/dev
          planfile: .planfile
        continue-on-error: true
