name: Release published

on:
  workflow_dispatch: 
# TODO: After testing released_published_test reinstate this
#  release:
#    types:
#      - published

permissions:
  id-token: write # This is required for aws oidc connection
  contents: read # This is required for actions/checkout.

env:
  TERRAFORM_VERSION: 1.6.6
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  HUSKY: 0

jobs:
  terraform_apply_prod:
    uses: ./.github/workflows/terraform_apply.yaml
    name: Terraform Apply - Prod
    with:
      stage: prod
      terraform_version: 1.6.6
      use_artifacts: false
      ref: ${{ github.event.release.tag_name }}
    secrets: inherit

  deploy_siri_vm_generator_ecs_task:
    uses: ./.github/workflows/deploy_ecs_manual.yaml
    name: Deploy ECS Task to Prod - siri-vm-generator
    needs: terraform_apply_prod
    with:
      environment: prod
      branch: ${{ github.event.release.tag_name }}
      task: siri-vm-generator

  deploy_siri_sx_generator_ecs_task:
    uses: ./.github/workflows/deploy_ecs_manual.yaml
    name: Deploy ECS Task to Prod - siri-sx-generator
    needs: terraform_apply_prod
    with:
      environment: prod
      branch: ${{ github.event.release.tag_name }}
      task: siri-sx-generator

  deploy_bods_avl_processor_ecs_task:
    uses: ./.github/workflows/deploy_ecs_manual.yaml
    name: Deploy ECS Task to Prod - bods-avl-processor
    needs: terraform_apply_prod
    with:
      environment: prod
      branch: ${{ github.event.release.tag_name }}
      task: bods-avl-processor


