name: Release published

on:
  release:
    types:
      - published
  workflow_dispatch:

permissions:
  id-token: write # This is required for aws oidc connection
  contents: read # This is required for actions/checkout.

env:
  TERRAFORM_VERSION: 1.6.6
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  HUSKY: 0

jobs:
  terraform_apply_prod:
    uses: ./.github/workflows/terraform_apply.yaml
    name: Terraform Apply - Prod
    with:
      stage: "prod"
      terraform_version: 1.6.6
      use_artifacts: false
      ref: ${{ github.event.release.tag_name || github.ref_name }}
    secrets: inherit

  deploy_siri_vm_generator_ecs_task:
    uses: ./.github/workflows/deploy_ecs_manual.yaml
    name: Deploy siri-vm-generator to Prod
    needs: terraform_apply_prod
    with:
      environment: "prod"
      branch: ${{ github.event.release.tag_name || github.ref_name }}
      task: siri-vm-generator
    secrets: inherit

  deploy_siri_sx_generator_ecs_task:
    uses: ./.github/workflows/deploy_ecs_manual.yaml
    name: Deploy siri-sx-generator to Prod
    needs: terraform_apply_prod
    with:
      environment: "prod"
      branch: ${{ github.event.release.tag_name || github.ref_name }}
      task: siri-sx-generator
    secrets: inherit

  deploy_bods_avl_processor_ecs_task:
    uses: ./.github/workflows/deploy_ecs_manual.yaml
    name: Deploy bods-avl-processor to Prod
    needs: terraform_apply_prod
    with:
      environment: "prod"
      branch: ${{ github.event.release.tag_name || github.ref_name }}
      task: bods-avl-processor
    secrets: inherit


