name: Release published

on:
  release:
    types:
      - published


permissions:
  id-token: write # This is required for aws oidc connection
  contents: read # This is required for actions/checkout.

env:
  TERRAFORM_VERSION: 1.6.6
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  HUSKY: 0

jobs:
  terraform_apply_test:
    uses: ./.github/workflows/terraform_apply.yaml
    name: Terraform Apply - Test
    with:
      stage: test
      terraform_version: 1.6.6
      use_artifacts: false
      ref: ${{ github.event.release.tag_name }}
    secrets: inherit

  deploy_siri_vm_generator_ecs_task:
    uses: ./.github/workflows/deploy_ecs_manual.yaml
    name: Deploy ECS Task to Test- siri-vm-generator
    needs: terraform_apply_test
    with:
      environment: test
      branch: ${{ github.event.release.tag_name }}
      task: siri-vm-generator

  deploy_siri_sx_generator_ecs_task:
    uses: ./.github/workflows/deploy_ecs_manual.yaml
    name: Deploy ECS Task to Test - siri-sx-generator
    needs: terraform_apply_test
    with:
      environment: test
      branch: ${{ github.event.release.tag_name }}
      task: siri-sx-generator

  deploy_bods_avl_processor_ecs_task:
    uses: ./.github/workflows/deploy_ecs_manual.yaml
    name: Deploy ECS Task to Test - bods-avl-processor
    needs: terraform_apply_test
    with:
      environment: test
      branch: ${{ github.event.release.tag_name }}
      task: bods-avl-processor


