on:
  workflow_call:
    inputs:
      stage:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      stage:
        type: choice
        description: Stage
        required: true
        options:
          - dev
          - test

permissions:
  id-token: write # This is required for aws oidc connection
  contents: read # This is required for actions/checkout

jobs:
  integration_test:
    runs-on: ubuntu-latest
    name: Run integration tests
    env:
      STAGE: ${{ inputs.stage }}
    environment: ${{ inputs.stage }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9
          run_install: false

      - name: Get pnpm store directory
        run: echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('src/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE }}
          aws-region: ${{ vars.AWS_DEFAULT_REGION }}
          role-session-name: GitHub-OIDC-TERRAFORM

      - name: Install dependencies
        working-directory: ./integration-testing
        run: pnpm install

      - name: Run integration tests
        working-directory: ./integration-testing
        run: pnpm test

      - name: Upload integration test report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: integration-testing/playwright-report/
          retention-days: 30
