name: Zip function

on:
  workflow_call:
    inputs:
      function_dir:
        required: true
        type: string

jobs:
  zip_function:
    runs-on: ubuntu-22.04
    name: Zip function
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - uses: pnpm/action-setup@v3
        name: Install pnpm
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('src/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Build changed functions
        run: |
          cd ./src/functions/${{ inputs.function_dir }}
          pnpm i
          pnpm run build:ci

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.function_dir }}
          path: ./src/functions/${{ inputs.function_dir }}/dist/${{ inputs.function_dir }}.zip
