on:
  workflow_call:
    inputs:
      function_dir:
        required: true
        type: string

jobs:
  zip_function:
    runs-on: ubuntu-latest
    name: Zip function
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9
          run_install: false

      - name: Get pnpm store directory
        run: echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('src/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        working-directory: ./src/functions/${{ inputs.function_dir }}
        run: pnpm install

      - name: Run integration tests
        working-directory: ./src/functions/${{ inputs.function_dir }}
        run: pnpm build:ci

      - name: Upload function zip
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ${{ inputs.function_dir }}
          path: ./src/functions/${{ inputs.function_dir }}/dist/${{ inputs.function_dir }}.zip
